<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * http://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "Deutsch";

// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(

//Navigation
    'charset'                                         => 'ISO-8859-15',
    'd3mxextsearch'                                   => 'Extended Search',
    'd3mxextsearch_settings'                          => 'Settings',
    'd3mxextsearch_statistic'                         => 'Statistic',
    'd3mxextsearch_syneditor'                         => 'Synonym Editor',
    'd3tbclextsearch_syneditor_main'                  => 'Main',
    'd3tbclextsearch_syneditor_manage'                => 'Edit synonyms',
    'd3tbclextsearch_syneditor_family'                => 'Synonym family',
    'd3tbclextsearch_syneditor_synset'                => 'Edit synonym group',
    'd3tbclextsearch_settings_results'                => 'Base Settings',
    'd3tbclextsearch_settings_navigation'             => 'Filters + Display Settings',
    'd3tbclextsearch_settings_quick'                  => 'Quicksearch',
    'd3tbclextsearch_settings_browser'                => 'Browser Plugins',
    'd3tbclextsearch_settings_content'                => 'Content Search',
    'd3tbclextsearch_settings_statistik'              => 'Statistic',

    'D3_EXTSEARCH_LIST_SETTLANG'                      => 'settings for language',

    'D3_EXTSEARCH_TRANSL'                             => 'Extended Search',

    'D3_EXTSEARCH_MAIN_DEBUGACTIVE_DESC'              => 'Der Debugmodus gibt die verwendeten Datenbankabfragen zur einfacheren Programmierung und Fehlersuche im Frontend aus. Deaktivieren Sie diesen bitte unbedingt für den Livebetrieb, da mit aktiviertem Debugmodus das Datenbank-Caching nicht verwendet wird.',
    'D3_EXTSEARCH_MAIN_MAINSETTINGS'                  => 'Common Settings',
    'D3_EXTSEARCH_MAIN_FIELDLIST'                     => 'these fields will used in similar and quicksearch<br>relevance => field name (example.: 50 => oxtitle)',
    'D3_EXTSEARCH_MAIN_SORTDEBUG'                     => 'result field analysis',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_DESC'                => 'Insert your search term. In the table you\'ll get all relevance values according to every field, which fits to the hit. You can change all relevance values "_IN_" in the "extended search" settings. "D3PUSH" is the articles importance. The relevance for each article in the result list ("d3Priority") is calculated by this formula: <blockquote>((sum from all "_IN_" fields) x D3PUSH) + D3PUSH</blockquote>..._PART_IN_... - search term is contained as part in content of these field<br>..._WORD_IN_... - search term is a single word in these field',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_START'               => 'start search',
    'D3_EXTSEARCH_MAIN_NOFIELDSDEFINED'               => '<b>There are no fields defined.</b><br>Standard: \'oxtitle\', \'oxsearchkeys\' and \'oxartnum\'',
    'D3_EXTSEARCH_MAIN_FIELDLIST_DESC'                => 'Tragen Sie hier die Artikel-Tabellenfelder ein, die bei der Suche verwendet werden. Die Feldbezeichnungen entnehmen Sie bitte der Shopdatenbank. Ändern Sie diese Eintragungen, muß der Suchindex noch einmal neu erzeugt werden.<br><br>Vor den Feldnamen tragen Sie mit => getrennt die Relevanz des jeweiligen Feldes ein. Je höher die Relevanz, umso höher wird ein Artikel gezeigt, wenn der Suchbegriff in diesem Feld vorkommt (separat zu aktivieren). Wird der Suchbegriff in mehreren Feldern gefunden, addiert sich die Relevanz. Ist keine Relevanz angegeben, erhält das Feld automatisch den Wert 10.',
    'SHOP_CONFIG_SEARCHFIELDS'                        => 'Fields to be considered in Search<br>"extended search" use own settings / edit in <input type="button" onclick="document.getElementById(\'myedit\').target = \'basefrm\'; document.getElementById(\'myedit\').fnc.value=\'\';document.getElementById(\'myedit\').cl.value=\'d3_cfg_extsearch_main\';document.getElementById(\'myedit\').submit();" value="extended search">',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT'                 => 'allow included and excluded letters in search string',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT_DESC'            => 'Mit dieser Option wird auch nach Artikeln gesucht, in deren Texten ein Buchstabe mehr (eingeschoben) oder weniger (ausgelassen) vorkommt. Jedoch kann sich dadurch auch die Trefferzahl erhöhen und das Ergebnis aufweichen. Auf Singular <-> Plural-Treffer hat diese Einstellung keinen Einfluß.',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS'                  => 'use of multiple search words',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_DESC'             => 'Ist es sinnvoll, daß auch bei mehreren Suchworten diese nur im Zusammenhang gesucht werden, können Sie dies hier aktivieren. Andernfalls kann jedes der Suchworte separat und ohne eine Verbindung in den Ergebnissen vorkommen. Im Syntaxmodus kann der Nutzer den Modus selbst bestimmen, in dem er zusammenhängende Worte in Anführungszeichen setzt und/oder mit Plus- oder Minus-Zeichen einschränkt bzw. ausweitet.',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SINGLE'           => 'every word will searched separatly',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_WHOLE'            => 'will used as complete string',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SYNTAX'           => 'user controlled by search syntax',
    'D3_EXTSEARCH_MAIN_VARIANTSETTINGS'               => 'Variant Search',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH'                 => 'Shop sucht auch nach Variantenartikeln',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE'                  => 'wird eine Artikelvariante gefunden, wird ...',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWPARENT'       => '... deren Vaterartikel in der Trefferliste gezeigt',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWVARIANT'      => '... die Variante selbst in der Trefferliste gezeigt',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_DESC'             => 'Beachten Sie bei der Anzeige des Vaterartikels anstatt der Variante bitte darauf, dass die Vaterartikel auch aktiv und auswählbar sein müssen. Eine zusätzliche Prüfung darauf findet absichtlich nicht statt, da diese das Suchergebnis verfälschen würde.',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH_DESC'            => 'Statt wie üblich nur nach regulären Artikeln zu suchen, findet der Shop mit dieser Option auch einzelne Variantenartikel. Tragen Sie bitte zusätzlich in der Feldliste \'oxvarselect\' ein und generieren Sie den Suchindex neu.',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS'                 => 'check for additional search param form fields',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS_DESC'            => 'Erweitern Sie das Suchformular mit weiteren Filtermöglichkeiten. Um diese auch zu verwenden, muß dieser Haken gesetzt sein. Detailierte Erklärungen zu weiteren Suchfeldern finden Sie im Dokumentations-Ordner des Moduls.',
    'D3_EXTSEARCH_MAIN_LOGSETTINGS'                   => 'Statistic',
    'D3_EXTSEARCH_MAIN_LOGHITLESS'                    => 'ergebnislose Suchaktionen für Statistik mitschreiben',
    'D3_EXTSEARCH_MAIN_LOGHITLESS_DESC'               => 'Startet der Kunde eine Suchanfrage, die keine Ergnisse liefern kann, werden die Suchbegriffe für Sie aufgezeichnet. Sie finden die Aufstellung dann unter der Registerkarte \'Logging\' und können Ihre Produkte ggf. auch für diese Begriffe optimieren.',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH'                  => 'alle Suchanfragen für Statistik mitschreiben (auch ohne shopweites Logging)',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH_DESC'             => 'Schreibt alle Suchanfragen für die modulinterne Statistik mit. Diese Einstellung kann auch gesetzt werden, ohne daß andere Shopfunktionen mitgeschrieben werden. Ist das shopweite Logging aktiviert, werden die Suchanfragen generell mitgeschrieben.',
    'D3_EXTSEARCH_MAIN_PHONETICS'                     => 'Phonetic Search (search for similar sound)',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH'                 => 'wenn kein Suchergebnis, Shop sucht nach ähnlichen klingenden Artikel (Bsp.: Suche: <i>Pflan<b>s</b>e</i>, Treffer: <i>Pflan<b>z</b>e</i>)',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH_DESC'            => 'Hier aktivieren (oder deaktivieren) Sie die phonetische Suche. Damit fangen Sie zum Beispiel Schreibfehler in der Suchabfrage ab und der Kunde findet seine gewünschten Artikel trotzdem mit großer Wahrscheinlichkeit. Ist gleichzeitig die Suche nach Sinn (Semantic) aktiviert, wird zuerst versucht, sinngleiche Treffer zu finden. Schlägt dies fehl, werden Treffer über die Klangsuche ermittelt.',
    'D3_EXTSEARCH_MAIN_PHONETICLANG'                  => 'für die Ähnlichkeitssuche verwendete Sprache',
    'D3_EXTSEARCH_MAIN_PHONETICLANG_DESC'             => 'Da sich die verschiedenen menschlichen Sprachen in Ihrer Aussprache und in der Wort- bzw. Buchstabenzusammensetzung unterscheiden, ist für ein optimales Suchergebnis ein sprachenabhängiges Verfahren zur Indexgenerierung nötig. Sollten Sie in Ihrem Shop hauptsächlich eine andere Sprache als die nebenstehend Angezeigte verwenden, fragen Sie bei uns nach, ob auch ein Modul für Ihre Sprache zur Verfügung steht.',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_1'              => 'Shop zeigt zusätzlich ähnliche klingende Treffer, wenn reguläre Suche maximal',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_2'              => 'Treffer',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_DESC'           => 'Wenn die Suche nur wenige Treffer erzielt, kann man dem Kunden so auch ähnliche Artikel liefern. Diese ähnlichen Artikel werden in der Ergebnisliste nach den tatsächlichen Treffern gezeigt. Der Kunde wird mit einer Meldung über die aufgefüllte Liste informiert. Setzen Sie diese Einstellung bitte jedoch mit Bedacht ein, da die zusätzlichen Treffer die Kunden verwirren könnten.',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH'                 => 'Treffergenauigkeit bei kurzen Suchworten',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_LESS'            => 'weniger Genauigkeit',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_REG'             => 'normale Genauigkeit',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_MORE'            => 'mehr Genauigkeit',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_DESC'            => 'Für eine sinnvolle Trefferliste ist ein ausreichend langes Suchwort nötig. Je \'genauer\' Sie diese Einstellung setzen, umso präziser sind die Treffer.',
    'D3_EXTSEARCH_MAIN_SEMANTICS'                     => 'Semantic Search (search for similar type)',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH'                => 'Shop sucht nach Artikeln mit ähnlichem Sinn (Bsp.: Suche: <i>Gew&auml;chs</i>, Treffer: <i>Pflanze</i>)',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_MISSING'        => 'Shop sucht nach Artikeln mit ähnlichem Sinn (Bsp.: Suche: <i>Gew&auml;chs</i>, Treffer: <i>Pflanze</i>)<br><b>Lexikon ist nicht installiert!</b>',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_DESC'           => 'Setzen Sie diesen Haken, um eine sinngleiche Suche im Shop zu ermöglichen. Durch z.B. regionale Unterschiede kann es vorkommen, daß Ihre Kunden einen Artikel zwar anders bezeichnen, jedoch Ihr Produkt meinen. Gibt der Kunde nun seinen Wunsch ein, bekommt er gegebenenfalls die Begriffe gezeigt, die in Ihrem Shop das gewünschte Produkt besser beschreiben.',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC'           => 'enthält das Suchwort Schreibfehler, wird zusätzlich zur Sinnsuche versucht, die richtige Schreibweise zu ermitteln; erzeugt jedoch ggf. stark abweichende Treffer; erfordert aktivierte phonetische Suche',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC_DESC'      => 'Diese Einstellung erlaubt zur sinngleichen Suche auch die phonetische Suche, wenn keine sinngleichen Worte gefunden werden. Da hier jedoch der gewünschte Sinn nicht eindeutig klar ist, werden unter Umständen stark abweichende Treffer gezeigt. Wir empfehlen die Verwendung dieser Einstellung nur eingeschränkt.',
    'D3_EXTSEARCH_MAIN_SEMANTICALLOWVULGAR'           => 'auch sinngemäße derbe und vulgäre Worte verwenden',
    'D3_EXTSEARCH_MAIN_SAVE'                          => 'save',
    'D3_EXTSEARCH_MAIN_INDEX'                         => 'Search Index',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT'                   => 'Artikel pro Durchlauf für Index aufarbeiten',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT_DESC'              => 'Der Webserver bricht Scripte nach einer gewissen Laufzeit aus Sicherheitsgründen ab. Um die Generierung des Suchindexes dennoch fertigstellen zu können, verarbeitet dieses Script nur eine gewisse Anzahl Artikel und startet sich dann neu. Legen Sie hier fest, wie viele Artikel in einem Durchlauf bearbeitet werden sollen. Bricht die Generierung mit einem Fehler ab, reduzieren Sie die Zahl. Je niedriger die Anzahl, um so länger benötigt jedoch das Script.',
    'D3_EXTSEARCH_MAIN_INDEXERR'                      => 'Der benötigte Index für die fehlertolerante Suche ist lückenhaft. Klicken Sie hier, um die Liste neu zu generieren:',
    'D3_EXTSEARCH_MAIN_INDEXNOERR'                    => 'Der benötigte Index für die fehlertolerante Suche scheint vollständig. Im Moment ist keine Aktion nötig, wenn Sie die Sprache nicht geändert haben oder Artikel importiert haben.<br>Der Index muß für jede Spache des Shop separat erstellt werden.',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL'                  => 'Suchindex komplett neu generieren',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL_DESC'             => 'Generiert für alle im Shop vorhandenen Artikel den Suchindex neu. Dies kann unter Umständen länger dauern.',
    'D3_EXTSEARCH_MAIN_GENINDEXNEW'                   => 'neue Artikel in Suchindex aufnehmen',
    'D3_EXTSEARCH_MAIN_GENINDEXNEW_DESC'              => 'Klicken Sie auf die nebenstehende Schaltfläche, um alle Artikel, die seit der letzten Indizierung geändert oder hinzugefügt wurden, in den Suchindex aufzunehmen. Alle bisherigen Artikel werden dabei ignoriert.',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX'              => 'Lexikon für sinngleiche Suche neu indizieren',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX_DESC'         => 'Für die Verbindung von sinngleicher Suche und phonetischer Suche benötigt auch das Lexikon den phonetischen Index. Mit dieser Schaltfläche starten Sie die Neuindizierung des Lexikons. Im Normalfall ist dies jedoch nicht notwendig.',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY'               => 'sort hits by relevance',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY_DESC'          => 'Hat der Kunde keine eigene Sortierung gewählt, werden die Suchtreffer nach Feldrelevanz sortiert. Die Relevanz legen Sie an den für die Suche definierten Datenbankfeldern fest. Die Summe der Relevanz der Felder, die den Suchbegriff enthalten, wird dann als Sortierkriterium verwendet. In Verbindung mit der Wichtigkeit der Artikel (separat zu aktivieren) kann sich die Relevanz vervielfachen.<br><br>Formel: <br>Sortierung = Relevanzsumme * Wichtigkeit + Wichtigkeit',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH'                   => 'sort hits by importance',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH_DESC'              => 'Hat der Kunde keine eigene Sortierung gewählt, werden die Suchtreffer nach Wichtigkeit sortiert. Die Wichtigkeit legen Sie am jeweiligen Artikel fest. Ohne aktivierte Feldrelevanz ist die Wichtigkeit einziges Sortierkriterium. In Verbindung mit Feldrelevanz wirkt die Wichtigkeit als Multiplikator. Treffer in niedrig priorisierten Feldern bei wichtigen Artikeln können diese damit vor unwichtige Artikel mit hohen Feldrelevanz setzen und die Reihenfolge so ggf. umkehren.<br><br>Formel: <br>Sortierung = Relevanzsumme * Wichtigkeit + Wichtigkeit',
    'D3_EXTSEARCH_MAIN_SHOW_POPUP'                    => 'show popup while searching',
    'D3_EXTSEARCH_MAIN_CATEGORY'                      => 'Search in category data',
    'D3_EXTSEARCH_MAIN_CATEGORY_SEARCH'               => 'auch in Kategorienamen suchen und enthaltene Artikel finden',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTHANDLING'          => 'Kategorie selbst oder deren Artikel anzeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTINCAT'             => 'Artikel aus Kategorie anzeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY_CATINLIST'            => 'Kategorie zur Auswahl anzeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY'             => 'Relevanz bei Kategorietreffern',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY_DESC'        => 'Kategorietreffer erhalten diese Relevanz, wenn die Relevanzsortierung aktiviert ist. Hierbei steht diese Zahl im Zusammenhang mit den Feldrelevanz (siehe separate Einstellung).',
    'D3_EXTSEARCH_MAIN_MANUFACTURER'                  => 'Suche in Marken und Lieferanten',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_SEARCH'           => 'auch in Marken- und Lieferantennamen suchen und enthaltene Artikel finden',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY'         => 'Relevanz bei Marken-/Lieferantentreffern',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY_DESC'    => 'Marken-/Lieferantentreffer erhalten diese Relevanz, wenn die Relevanzsortierung aktiviert ist. Hierbei steht diese Zahl im Zusammenhang mit den Feldrelevanz (siehe separate Einstellung).',
    'D3_EXTSEARCH_MAIN_ADMINPANEL'                    => 'admin panel',
    'D3_EXTSEARCH_MAIN_ADMINSHOWVARIANTS'             => 'in searchresults show variants in article list too',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH'               => 'speziell nach Artikelnummern suchen',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH_DESC'          => 'mit dieser Einstellung wird vor dem eigentlichen Suchlauf gezielt nach Artikeln gesucht, die den Suchbegriff als Artikelnummer haben.',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS'             => 'Datenbankabfragen verwenden <b>nicht</b> die moduleigenen View-Tabellen',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS_DESC'        => 'Aus Performance-Gründen verwendet die Suche nicht die shopeigenen View-Tabellen, sondern bringt optimierte Versionen dessen mit. Je nach Größe des Datenbank kann deren Verwendung die Geschwindigkeit von Datenbankabfragen bis um den Faktor 100 beschleunigen. Sollen die spezialisierten View-Tabellen <b>nicht</b> verwendet werden, setzen Sie diesen Haken. Dann werden die Abfragen über die shopeigenen View-Tabellen geleitet.<br>Beachten Sie, dass bei deaktivierung dieser Option die View-Tabellen noch einmal aktualisiert werden müssen.',

    'D3_EXTSEARCH_NAVI_MAINSETTINGS'                  => 'Common Settings',
    'D3_EXTSEARCH_NAVI_DISPTYPE'                      => 'Art der Filter-Anzeige',
    'D3_EXTSEARCH_NAVI_DISPTYPE_LINKLIST'             => 'as link list',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DROPDOWN'             => 'as dropdown list (requires java script)',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DESC'                 => 'Stellen Sie hier die Anzeigeform der Kategorie-, Lieferanten- und Markenlisten ein. Die DropDown-Listen sparen in der Anzeige Platz, können jedoch bei vielen Einträgen unübersichtlich lang werden. Außerdem benötigen sie beim Kunden JavaScript. Alternativ empfehlen sich Linklisten, die in ihrer Länge auch eingeschränkt werden können.<br>Beide Anzeigeformen lassen sich im Template nachbearbeiten.',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH'                   => 'Suche ohne Suchbegriff zulassen',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH_DESC'              => 'Es kann durchaus sinnvoll sein, auch Suchvorgänge ohne einen Suchbegriff zuzulassen. Möglicherweise werden die dann erhaltenen Treffer erst durch eine zusätzliche Einstellung gefiltert oder Sie möchten ein umfangreiches Suchformular aufbauen, welches möglicherweise kein frei definierbares Suchwort enthält.',
    'D3_EXTSEARCH_NAVI_CATFILTER'                     => 'Category Filter',
    'D3_EXTSEARCH_NAVI_CATLIST'                       => 'show category list',
    'D3_EXTSEARCH_NAVI_CATLIST_DESC'                  => 'Setzen Sie den Haken, um Ihrem Kunden bei einer umfangreichen Trefferliste eine Auswahl der betroffenen Kategorien anzuzeigen. Damit kann er sein Suchergebnis gezielt einschränken und damit verbessern. Angezeigt wird der Kategoriename und die Anzahl der darin enthaltenen Artikel der Trefferliste.',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT'                  => 'sort by',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_COUNT'            => 'count of related articles',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DATA'             => 'defined sort',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DESC'             => 'Legen Sie hier fest, nach welchem Kriterium die Kategorieliste sortiert sein soll. Auf die Darstellung hat dies jedoch keinen Einfluß.',
    'D3_EXTSEARCH_NAVI_CATLIST_ONEITEM'               => 'show category list too, if there\'s 1 item in list only',
    'D3_EXTSEARCH_NAVI_CATLIST_ONEITEM_DESC'          => 'Werden bei der Suche nur Artikel gefunden, die sich in nur einer einzigen Kategorie befinden, können Sie die Anzeige der Kategorieliste für diesen Sonderfall deaktivieren. Dies funktioniert nur bei Anzeigetyp "Linkliste".',
    'D3_EXTSEARCH_NAVI_VENDORFILTER'                  => 'Vendor Filter',
    'D3_EXTSEARCH_NAVI_VENDORLIST'                    => 'show vendor list',
    'D3_EXTSEARCH_NAVI_VENDORLIST_DESC'               => 'Ebenso wie für die Kategorien gibt es auch die Möglichkeit, die Trefferliste noch einmal nach den Lieferanten zu filtern. Dies schalten Sie hier ein. Diese Option ist nur verfügbar, wenn Sie generell die Lieferantent im Shop aktiviert haben und auch eine Suche danach erlauben. (\'Lieferantenliste laden und anzeigen\')',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT'               => 'sort by',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_COUNT'         => 'count of related articles',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_ALPHA'         => 'alphabetical',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_DESC'          => 'Bestimmen Sie die Anzeigereihenfolge, in der die Lieferanten aufgelistet sein sollen.',
    'D3_EXTSEARCH_NAVI_VENDORLIST_ONEITEM'            => 'show vendor list too, if there\'s 1 item in list only',
    'D3_EXTSEARCH_NAVI_VENDORLIST_ONEITEM_DESC'       => 'Wird nur ein Lieferant in der Trefferliste gefunden, kann die Anzeige den Kunden womöglich verwirren. Deaktivieren Sie die Anzeige dann hier. Dies funktioniert nur bei Anzeigetyp "Linkliste".',
    'D3_EXTSEARCH_NAVI_MANUFACTURERFILTER'            => 'Brand Filter',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST'              => 'show brand list',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_DESC'         => 'Ebenso wie für die Kategorien gibt es auch die Möglichkeit, die Trefferliste noch einmal nach den Marken zu filtern. Dies schalten Sie hier ein. Diese Option ist nur verfügbar, wenn Sie generell die Marken im Shop aktiviert haben und auch eine Suche danach erlauben. (\'Markenliste laden und anzeigen\')',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT'         => 'sort by',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_COUNT'   => 'count of related articles',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_ALPHA'   => 'alphabetical',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_DESC'    => 'Bestimmen Sie die Anzeigereihenfolge, in der die Marken aufgelistet sein sollen.',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_ONEITEM'      => 'show brand list too, if there\'s 1 item in list only',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_ONEITEM_DESC' => 'Wird nur eine Marke in der Trefferliste gefunden, kann die Anzeige den Kunden womöglich verwirren. Deaktivieren Sie die Anzeige dann hier. Dies funktioniert nur bei Anzeigetyp "Linkliste".',
    'D3_EXTSEARCH_NAVI_CONTENTS'                      => 'Information pages / CMS Texts',
    'D3_EXTSEARCH_NAVI_CONTENTLIST'                   => 'search in CMS pages',
    'D3_EXTSEARCH_NAVI_CONTENTLIST_DESC'              => 'Neben Artikeln können Sie auch entsprechend markierte Texte suchen lassen. Setzen Sie dazu den entsprechenden Haken bei den jeweiligen CMS-Bausteinen (\'Kundeninformationen > CMS-Seiten\').',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEFILTER'               => 'Attribute Filter',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST'                 => 'show attribute list',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_DESC'            => 'Aktivieren Sie diese Option, wenn auch in Attributen gesucht werden soll. Empfehlenswert ist hierbei, die Listenansicht af Dropdown zu stellen, da sonst die Übersichtlichkeit sehr leiden kann.<br>Every attribute can excluded from usage on its setting page.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT'            => 'sort by',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_COUNT'      => 'count of related articles',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_POS'        => 'defined attribute position',
    'D3_EXTSEARCH_NAVI_NOATTRIBUTEARTS'               => 'auch nach nicht dem jeweiligen Attribut zugeordneten Artikeln filtern',
    'D3_EXTSEARCH_NAVI_CONTENTSEARCHINLONGTEXT'       => 'search in CMS longtexts too',
    'D3_EXTSEARCH_NAVI_CONTENTLONG_DESC'              => 'Legen Sie fest, ob auch in den Langtexten der CMS-Bausteine gesucht werden soll.',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS'                => 'Kategorie-, Lieferanten-, Marken- und Textlisten begrenzen<br>(Kunde kann alle Treffer auf Wunsch anzeigen, funktioniert nur bei "Linklisten")',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_2'              => ' Einträge',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_DESC'           => 'Bei vielen Suchtreffern kann auch die Kategorie-, Marken-, Lieferanten- und Textliste sehr lang werden. Die Artikeltreffer rutschen so vielleicht nach unten aus dem Anzeigebereich heraus. Beschränken Sie die Anzahl der angezeigten Kategorien und Marken, um diese Listen kurz zu halten. Werden diese Listen dann tatsächlich gekürzt, steht Ihrem Kunden eine Schaltfläche zur Verfügung, um diese Listen auf Wunsch komplett anzuzeigen.',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT'                     => 'bei 1 Suchergebnis, Shop wechselt direkt zur Detailseite des Artikels bzw. des Textes',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT_DESC'                => 'Hat Ihr Kunde so präzise gesucht, daß er die gewünschte Information als Einziges in der Trefferliste hat, können Sie ihm den Umweg über die Trefferliste ersparen und liefern ihm sofort die Detailseite des gefunden Artikels bzw. des Textes.',
    'D3_EXTSEARCH_NAVI_PRICELIST'                     => 'show price steps',
    'D3_EXTSEARCH_NAVI_PRICEFILTER'                   => 'Price Filter',
    'D3_EXTSEARCH_NAVI_PRICELIST_DESC'                => 'Alle gefundenen Artikel werden in Preiskategorien aufgeteilt und diese als weitere Filterkriterien angeboten. So kann der Kunde eine gewisse Preisspanne für seine gewünschten Artikel wählen. Rabatte sind in den Kategoriepreisen nicht berücksichtig. Gefundene Artikel sind in dem Fall preiswerter, als die Suchanfrage vorgibt.',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS'               => 'maximum count of price steps',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS_DESC'          => 'So viele Preisspannen werden maximal angezeigt. Im Normalfall kann dies jedoch weniger sein, da leere Preisspannen (also ohne enthaltene Artikel) ausgefiltert werden.',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED'             => 'price limits will rounded',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED_DESC'        => 'Die kleinste Preisspanne beginnt beim kleinstmöglichen Preis, die größte Preisspanne erstreckt sich bis zum höchten Preis. Die Grenzen dazwischen werden errechet. Diese können unter Umständen jedoch bei krummen Cent-Beträgen liegen. Mit der Option werden die Preise der Spannen gerundet, die Spannen sind jedoch dann weniger aussagekräftig.',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY'             => 'price steps display type',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_LISTTYPE'    => 'as dropdown',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_SLIDER'      => 'as jQuery slider',
    'D3_EXTSEARCH_NAVI_PRICELIST_REQU'                => '* jQuery slider requires installed jQuery framework in actual version (tried with version 1.4.2) with components "jQueryUI Core", "jQueryUI Widget", "jQueryUI Mouse" and "jQueryUI Slider".',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT'                     => 'gefundene Textstellen werden in Suchergebnissen hervorgehoben',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT_DESC'                => 'Manchmal taucht der gesuchte Begriff erst mitten in Beschreibungen auf. Mit dieser Option heben Sie den Begriff optisch hervor.<br><br>Stellen Sie dazu im Template \'d3_ext_search_highlight.tpl\' ein, wie die Hervorhebung aussehen soll. Ersetzen Sie dann in \'inc/product.tpl\' alle Variablen, die Hervorhebungen enthalten sollen, gegen den Smarty-Aufruf \[\{ d3_extsearch_highlight text=$variablenname \}\], wobei $variablenname gegen die tatsächliche Textvariable ersetzt wird.',
    'D3_EXTSEARCH_NAVI_INDEXFILTER'                   => 'Index Letters',
    'D3_EXTSEARCH_NAVI_SHOWINDEX'                     => 'show index letters',
    'D3_EXTSEARCH_NAVI_SHOWINDEX_DESC'                => 'Der Buchstabenindex gibt Ihren Kunden die Möglichkeit, die Suchtreffer weiter nach dem Anfangsbuchstaben einzuschränken.<br><br>Die Buchtabenliste selbst können Sie im Template \'d3_inc_ext_search.tpl\' bearbeiten.',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME'               => 'Feldname, nach dem gefiltert wird',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME_DESC'          => 'Möglich sind hier alle Felder aus der Tabelle oxarticles.',
    'D3_EXTSEARCH_NAVI_SAVE'                          => 'save',

    'D3_EXTSEARCH_QUICK'                              => 'Schnelltreffer',
    'D3_EXTSEARCH_QUICK_ACTIVE'                       => 'bei Eingabe des Suchbegriffs werden Vorschläge geliefert (wird nur bei Nutzern mit aktiviertem JavaScript angezeigt)',
    'D3_EXTSEARCH_QUICK_ACTIVE_DESC'                  => '<img src="../modules/d3/d3_extsearch/out/admin/img/d3_extsearch_quicksearch.jpg"><br>Geben Sie Ihrem Kunden die Möglichkeit, Artikel noch schneller zu finden. Die Schnellsuche stellt schon während der Eingabe des Suchbegriffs die ersten Treffer in einem eigenen Rahmen dar.',
    'D3_EXTSEARCH_QUICK_COUNT'                        => 'maximale Anzahl der zu ladenden Artikel in der Schnellsuche',
    'D3_EXTSEARCH_QUICK_COUNT_DESC'                   => 'Aus Performancegründen werden die Schnellsuchtreffer erst ab einer maximalen Anzahl gezeigt. Werden mehr Treffer gefunden, blendet sich die Artikelliste nicht ein, statt dessen wird ein Hinweis gezeigt. Erhöhen Sie den Wert, wenn Sie für häufig vorkommende Suchbegriffe keine Schnelltreffer erhalten. Kontrollieren Sie aber bitte unbedingt danach die Last Ihres Servers / Accounts. Der Standardwert ist 200.',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES'               => 'zusätzlich auch nach entsprechend benannten Kategorien suchen',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES_DESC'          => 'Neben Artikeln werden in der Schnellsuche auch Kategorien gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS'            => 'zusätzlich auch nach entsprechend benannten Marken suchen',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS_DESC'       => 'Neben Artikeln werden in der Schnellsuche auch Marken gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_LOADVENDORS'                  => 'zusätzlich auch nach entsprechend benannten Lieferanten suchen',
    'D3_EXTSEARCH_QUICK_LOADVENDORS_DESC'             => 'Neben Artikeln werden in der Schnellsuche auch Lieferanten gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_LOADCONTENT'                  => 'zusätzlich auch nach entsprechend benannten Texten suchen',
    'D3_EXTSEARCH_QUICK_LOADCONTENT_DESC'             => 'Neben Artikeln werden in der Schnellsuche auch Texte gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_CMPLOBJ'                      => 'vor Oxid 4.3.0: komplettes Artikel-Objekt laden, sonst nur ID, Titel und Icon.<br>Nur bei Bedarf aktivieren, verbraucht mehr Ressourcen. ',
    'D3_EXTSEARCH_QUICK_CMPLOBJ_DESC'                 => 'Die Darstellung der Schnelltreffer kann von Ihnen in einem Template grafisch an Ihren Shop angepaßt werden. Vielleicht benötigen Sie für Ihre gewünschte Darstellung noch weitere Daten außer dem Arikelnamen und dem Link zum Artikel. So lassen sich z.B. auch Miniaturbilder, der Preis oder auch gleich ein Warenkorbbutton einblenden. Dazu benötigen Sie jedoch Informationen, die so im Standard nicht verfügbar sind. Setzen Sie diesen Haken, um alle Artikeldaten verfügbar zu machen.<br><br>Ab Shopversion 4.3.0 ist es unbedingt notwendig, das komplette Artikelobjekt zu laden. Diese Einstellung wird dann ignoriert.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS'                 => 'Variantenartikel laden und in der Schnellsuche anzeigen<br>Tragen Sie dazu in den Suchfeldern zusätzlich \'oxvarselect\' ein.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS_DESC'            => 'Normalerweise sucht die Shopsuche nicht nach Artikelvarianten. Haben Sie jedoch viele Variantenartikel in Ihrem Shop, kann es sinnvoll sein, die Suche dafür freizuschalten.',
    'D3_EXTSEARCH_QUICK_SAVE'                         => 'save',
    'D3_EXTSEARCH_QUICK_TPLNOTICE'                    => 'Hinweis: Um das Fenster der Schnellsuche grafisch anzupassen, verwenden Sie bitte das Template \'d3_ext_search_quicksearch.tpl\'.',
    'D3_EXTSEARCH_QUICK_IAS'                          => 'interaktive Suche (Markier-Suche)',
    'D3_EXTSEARCH_QUICK_SHOWIAS'                      => 'zeige interaktive Suche (Markier-Suche)',
    'D3_EXTSEARCH_QUICK_SHOWIAS_DESC'                 => 'Markieren Sie im Shop ein Wort, wird Ihnen in dessen Nähe ein kleines Formular eingeblendet, mit dessen Hilfe Sie sofort nach dem markierten Wort suchen können. Klicken Sie an eine andere Stelle im Shop, verschwindet das Fenster wieder.',

    'D3_EXTSEARCH_STAT_TYPE'                          => 'Auswertung:',
    'D3_EXTSEARCH_STAT_NOHITS'                        => 'keine Auswertungen vorhanden',
    'D3_EXTSEARCH_STAT_NOREPORTBASE'                  => 'Your shop doesn\'t support this statistics.',
    'D3_EXTSEARCH_STAT_TYPEHITLESS'                   => 'Suchabfragen ohne Treffer',
    'D3_EXTSEARCH_STAT_TYPEMOSTHITS'                  => 'Suchabfragen mit den meisten Treffern',
    'D3_EXTSEARCH_STAT_TYPEMOSTSEARCHES'              => 'häufigste Suchbegriffe',
    'D3_EXTSEARCH_STAT_TIME'                          => 'Zeitraum:',
    'D3_EXTSEARCH_STAT_GENERATESTAT'                  => 'Auswertung erstellen',
    'D3_EXTSEARCH_STAT_SEARCHWORD'                    => 'search term',
    'D3_EXTSEARCH_STAT_HITS'                          => 'hits',
    'D3_EXTSEARCH_STAT_SEARCHES'                      => 'Anfragen',
    'D3_EXTSEARCH_STAT_TYPES_CATEGORY'                => 'category',
    'D3_EXTSEARCH_STAT_TYPES_PRICE'                   => 'price',
    'D3_EXTSEARCH_STAT_TYPES_VENDOR'                  => 'vendor',
    'D3_EXTSEARCH_STAT_TYPES_MANUFACTURER'            => 'brand',
    'D3_EXTSEARCH_STAT_TYPES_OWNLIKE'                 => 'own search field (LIKE)',
    'D3_EXTSEARCH_STAT_TYPES_OWNIS'                   => 'own search field (IS)',
    'D3_EXTSEARCH_STAT_TYPES_OWNVALUE'                => '%s => "%s"',
    'D3_EXTSEARCH_STAT_TYPES_ATTRIBUTE'               => 'attributes',
    'D3_EXTSEARCH_STAT_TYPES_INDEXLETTER'             => 'index letter',
    'D3_EXTSEARCH_STAT_TYPES_UNKNOWN'                 => 'unknown filter',
    'D3_EXTSEARCH_STAT_STATDESC_HITLESS'              => 'hitless searches in %s to "%s" ',
    'D3_EXTSEARCH_STAT_STATDESC_MOSTSEARCHES'         => 'searches in %s to "%s" ',

    'D3_EXTSEARCH_PLUGIN_SETTINGS'                    => 'settings',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE'                => 'dem Nutzer im Browser anbieten, das Such-Plugin zu installieren',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE_DESC'           => 'Im Internet Explorer ab Version 7 und auch im Firefox ab Version 2 finden Sie im rechten oberen Eck eine Möglichkeit, von jeder beliebigen Stelle im Internet aus die wichtigsten Suchmaschinen zu starten. Bieten Sie Ihren Kunden an, auch Ihren Shop in diese Liste hinzuzufügen. So reicht es, in der Drop-Down-Box Ihren Shop auszuwählen und den Suchbegriff einzugeben. Sofort wird Ihr Shop mit den Suchtreffern gezeigt. Als Text wird Ihr Shoptitel verwendet, ein Icon können Sie weiter unten festlegen.',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK'                 => 'einen Installationslink in der Shop-Suche anzeigen',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK_DESC'            => 'Kann Ihr Kunden Ihren Shop in die Suchmaschinenliste hinzufügen, wird dies im Browser durch eine farbige Umrandung angezigt. Dies ist jedoch nur wenig auffällig, viele Nutzer übersehen dies. Stellen Sie in den Suchergebnissen besser noch einen zusätzlichen Link dar, um auf diese Funktion hinzuweisen.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON'                  => 'Icon für Browserplugin',
    'D3_EXTSEARCH_PLUGIN_CHOOSEICON'                  => 'Bitte wählen Sie noch ein Icon.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON_DESC'             => 'Legen Sie hier das Icon fest, welches im Browser-Plugin angezigt werden soll. Das Icon muß ein Größe von 16 x 16 Pxeln haben und im PNG- oder JPG-Format vorliegen.',
    'D3_EXTSEARCH_PLUGIN_SAVE'                        => 'save',
    'D3_EXTSEARCH_PLUGIN_GENERATE'                    => 'Generierung',
    'D3_EXTSEARCH_PLUGIN_GENERATE_DESC'               => 'Haben Sie Ihren Shoptitel geändert, ein neues Icon festgelegt oder sogar Ihren Shop auf eine neue Adresse umgezogen, ist es nötig, das Suchplugin zu aktualisieren. Weisen Sie bitte auch Ihre Kunden darauf hin, das Plugin zu aktualisieren. Es erneuert sich nicht automatisch.',
    'D3_EXTSEARCH_PLUGIN_STARTGENERATING'             => 'Erstellung durchführen',
    'D3_EXTSEARCH_PLUGIN_GENERATEFILE'                => 'Installations-Datei erstellen:',
    'D3_EXTSEARCH_PLUGIN_GENERATENOTICE'              => 'Mit der Erstellung der Installations-Datei haben Sie alle erforderlichen Schritte durchgeführt. Startet Ihr Kunde die Integration, wird diese Datei automatisch von Ihrem Server ausgelesen.',

    'D3_EXTSEARCH REPORT_MOSTSEARCHES'                => 'Suchbegriffe (nur im Suchmodul verfgb.)',
    'D3_EXTSEARCH_STATISTIC_MOSTSEARCHES'             => 'häufigste Suchbegriffe',
    'D3_EXTSEARCH_STATISTIC_MOST_DESC'                => 'So oft wurde der gewählte Begriff gesucht',
    'D3_EXTSEARCH_STATISTIC_FURTHERFILTERS'           => '(durch weitere Filter eingeschränkt)',
    'D3_EXTSEARCH_STATISTIC_GRAPH'                    => 'grafische Auswertung',

    'D3_EXTSEARCH_CONTENT_SEARCHABLE'                 => '<img src="../modules/_d3modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> CMS is searchable',
    'D3_EXTSEARCH_PUSH'                               => '<img src="../modules/_d3modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> importance of these article in the whole assortment',
    'D3_EXTSEARCH_PUSH_1'                             => 'normal',
    'D3_EXTSEARCH_PUSH_2'                             => 'important',
    'D3_EXTSEARCH_PUSH_3'                             => 'very important',
    'D3_EXTSEARCH_PUSH_DESC'                          => 'D³ Modul "erweiterte Suche": Die Wichtigkeit definiert die erste Reihenfolge der Artikel in der Suche (bei Verwendung der "erweiterten Suche"). In Verbindung mit Feldrelevanz funktioniert die Wichtigkeit als Faktor. Besonders wichtige Artikel haben zum Beispiel die 3 fache Relevanz von normal gewichteten Artikeln. Beachten Sie dies auch bei der Vergabe der Feldrelevanz.',

    'D3_EXTSEARCH_ATTRIBUTE_NOTUSE4FILTER'            => '<img src="../modules/_d3modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> Attribute will not used in search filters',

    'D3_EXTSEARCH_SYNED_WORD'                         => 'Wort',
    'D3_EXTSEARCH_SYNED_ALTWORD'                      => 'sinnähnliche Worte',
    'D3_EXTSEARCH_SYNED_CATEGORY'                     => 'Kategorie',
    'D3_EXTSEARCH_SYNED_SYNSETID'                     => 'Synonym-ID',
    'D3_EXTSEARCH_SYNED_SAVENEWSYN'                   => 'neues Synonym speichern',
    'D3_EXTSEARCH_SYNED_DELETESYN'                    => 'Soll das Synonym wirklich gelöscht werden?',

    'D3_EXTSEARCH_SYNED_MAIN_NEWWORD'                 => 'Neues Wort / Wortgruppe',

    'D3_EXTSEARCH_SYNED_NOLEXICON'                    => 'The semantic lexicon isn\'t installed! Please check manual for further informations.',
    'D3_EXTSEARCH_SYNED_MAIN_WORD'                    => 'Wort / Wortgruppe:',
    'D3_EXTSEARCH_SYNED_MAIN_NORMALIZEDWORD'          => 'vereinfachtes Wort:',
    'D3_EXTSEARCH_SYNED_MAIN_ISACRONYM'               => 'ist eine Abkürzung:',
    'D3_EXTSEARCH_SYNED_MAIN_COMMENT'                 => 'Kommentar:',
    'D3_EXTSEARCH_SYNED_MAIN_SYNSETID'                => 'Synonym-ID:',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE'                => 'Sprache:',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_'               => 'undefiniert',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_EN'             => 'Englisch',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DE'             => 'Deutsch',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DISABLED'       => '(deaktiviert)',
    'D3_EXTSEARCH_SYNED_MAIN_GRAMMAR'                 => 'Grammatik:',
    'D3_EXTSEARCH_SYNED_MAIN_GRAMMAR_'                => 'undefiniert',
    'D3_EXTSEARCH_SYNED_MAIN_GRAMMAR_UNDEFINED'       => 'undefiniert',
    'D3_EXTSEARCH_SYNED_MAIN_GRAMMAR_BASE_FORM'       => 'Einzahl (Singular)',
    'D3_EXTSEARCH_SYNED_MAIN_GRAMMAR_PLURAL'          => 'Mehrzahl (Plural)',
    'D3_EXTSEARCH_SYNED_MAIN_LEVEL'                   => 'Wortart:',
    'D3_EXTSEARCH_SYNED_MAIN_LEVEL_2'                 => 'umgangssprachlich',
    'D3_EXTSEARCH_SYNED_MAIN_LEVEL_3'                 => 'derb',
    'D3_EXTSEARCH_SYNED_MAIN_LEVEL_4'                 => 'vulgär',
    'D3_EXTSEARCH_SYNED_MAIN_LEVEL_5'                 => 'fachsprachlich',
    'D3_EXTSEARCH_SYNED_MAIN_LEVEL_6'                 => 'gehoben',

    'D3_EXTSEARCH_SYNED_MANAGE_EDIT'                  => 'bearbeiten',
    'D3_EXTSEARCH_SYNED_MANAGE_SYNONYM'               => 'Synonym',

    'D3_EXTSEARCH_SYNED_FAMILY_GENERIC'               => 'Oberbegriff',
    'D3_EXTSEARCH_SYNED_FAMILY_GENERICNEW'            => 'neuen Oberbegriff speichern',
    'D3_EXTSEARCH_SYNED_FAMILY_ASSOZIATED'            => 'Assoziation',
    'D3_EXTSEARCH_SYNED_FAMILY_ASSOZIATEDNEW'         => 'neue Assoziation speichern',
    'D3_EXTSEARCH_SYNED_FAMILY_SUB'                   => 'Unterbegriff',
    'D3_EXTSEARCH_SYNED_FAMILY_SUBNEW'                => 'neuen Unterbegriff speichern',
    'D3_EXTSEARCH_SYNED_FAMILY_NOITEM'                => 'kein Eintrag vorhanden',

    'D3_EXTSEARCH_SYNED_SYNSET_VISIBLE'               => 'Aktiv',
    'D3_EXTSEARCH_SYNED_SYNSET_CATEGORY'              => 'Kategorie',

    'D3_EXTSEARCH_UPDATE_GENPHONETIC'                 => '"erweiterte Suche": Das Modulupdate führte Änderungen in der Datenbankstruktur für die Ähnlichkeitssuche aus. Aktualisieren Sie deshalb nach Abschluss dieser Installation den Suchindex im Adminbereich des Moduls.',

    'GENERAL_ARTICLE_D3_PHONETIC'                     => 'extSearch - phonetic index', // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3_SEARCHINDEXDATE'              => 'extSearch - date of last search index generating',
    // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3PUSH'                          => 'extSearch - product importance',
    // Multilang-Fields for importer
    'GENERAL_ARTICLE_OXVARSELECT'                     => 'variant title',

);


/*

[{oxmultilang ident="GENERAL_YOUWANTTODELETE"}]


*/
