<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * http://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(

//Navigation
    'charset'                                  => 'ISO-8859-15',
    'd3mxd3modules'                            => '<img src="../modules/_d3modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> Modules',
    'd3mxcfg'                                  => 'Module Connector',
    'd3mxcfgmod_settings'                      => 'Settings',
    'd3mxextensions'                           => 'module administration',
    'd3tbclext_installation'                   => 'module installation',
    'd3tbclext_status'                         => 'installed modules',
    'd3tbclext_new'                            => 'available modules',
    'd3mxlibs'                                 => 'libraries',
    'd3mxsysitems'                             => 'System Settings',
    'd3tbclmoditems'                           => 'Module items',
    'd3tbclcfgitems'                           => 'Config items',
    'd3tbclmaintenance'                        => 'maintenance',
    'd3tbclcfglibs'                            => 'Library settings',
    'd3tbcllib_status'                         => 'Status',
    'd3tbcllib_syscheck'                       => 'System Check',
    'd3tbcllib_support'                        => 'Support',

    'D3MODCFG_LIB_TRANSL'                      => 'Module Configuration',
    'D3MODCFG_LIB_HELPLINK'                    => 'Modul-Connector/Modul-Konfiguration/',

    'D3MODCFG_LIB_HELPLINK_STATUS'             => 'Update/',
    'D3MODCFG_LIB_HELPLINK_SUPPORT'            => 'Support/',
    'D3MODCFG_EXT_HELPLINK_STATUS'             => 'Extensions/',
    'D3MODCFG_EXT_HELPLINK_SUPPORT'            => 'Support/',

    'D3_MOD_LIB_INSTALLED'                     => 'installed libraries',
    'D3_MOD_EXT_INSTALLED'                     => 'installed modules',
    'D3_CFG_LIB_GETLIBLIST'                    => 'check for updates',
    'D3_CFG_LIB_GETDETAILS'                    => 'show details / settings',
    'D3_CFG_LIB_GETNEWLIBLIST'                 => 'check for updates again',
    'D3_CFG_LIB_CONNECTERROR'                  => 'Unable to connect with the connector update tool.\n\nPlease assure, that curl connections or serverspanned file connections are possible.',
    'D3_CFG_LIB_VERSION'                       => 'version',
    'D3_CFG_LIB_REVISION'                      => 'rev.',
    'D3_CFG_LIB_SHOPVERSION'                   => 'for shop version',
    'D3_CFG_LIB_INSTALLDATE'                   => 'installed at',
    'D3_CFG_LIB_NOTINSTALLED'                  => 'not installed',
    'D3_CFG_LIB_INSTALLED'                     => 'installed version',
    'D3_CFG_LIB_INSTALLEDVERSIONNOTCONGRUENT'  => 'The version declaration of the module aren\'t congruently. Maybe the installation isn\'t correct.',
    'D3_CFG_LIB_AVAILABLE'                     => 'available version',
    'D3_MOD_LIB_AVAIL_REMOTELIBS'              => 'available library',
    'D3_MOD_LIB_NOACTION'                      => 'no update required',
    'D3_MOD_LIB_INSTALL'                       => 'install module',
    'D3_MOD_LIB_REFRESH'                       => 'refresh module',
    'D3_MOD_EXT_REFRESH'                       => 'There\'s an update available for this module',
    'D3_MOD_LIB_NOUPDATEINFO'                  => 'no update informations available for this module',
    'D3_MOD_LIB_NODOWNLOAD'                    => 'no download available for this module',
    'D3_MOD_LIB_NOINSTALL'                     => 'no installation available for this module',
    'D3_MOD_LIB_OVERWRITE'                     => 'renew',
    'D3_MOD_LIB_DOWNLOAD'                      => 'download as file',
    'D3_MOD_LIB_BETA'                          => '(beta)',
    'D3_CFG_LIB_VERSIONUNKNOWN'                => 'unknown',
    'D3_CFG_LIB_FORMERVERSION'                 => 'last version',
    'D3_CFG_LIB_USEABLETO'                     => 'checked to shop',
    'D3_CFG_LIB_STATUS'                        => 'status',
    'D3_CFG_LIB_LIBRARY'                       => 'library',
    'D3_CFG_LIB_EXTENSION'                     => 'module',
    'D3_CFG_LIB_INFO'                          => 'info',
    'D3_CFG_LIB_INSTALLATION'                  => 'install.',
    'D3_CFG_LIB_DOWNLOADIT'                    => 'downl.',
    'D3_CFG_LIB_UPDATE'                        => 'update',
    'D3_CFG_LIB_MAINTENANCEMODE'               => 'Because of maintenance works ... Auf Grund von Wartungs- und Update-Arbeiten steht Ihnen die Aktualisierung leider kurzzeitig nicht zur Verfügung. Bitte versuchen Sie es zu einem späteren Zeitpunkt erneut. Vielen Dank für Ihr Verständnis.',

    'd3tbcl_licence'                           => 'Support',
    'D3_CFG_MOD_LIST_SETTLANG'                 => 'settings for language',

    'D3_CFG_MOD_GENERAL_MODULEACTIVE'          => 'module active',
    'D3_CFG_MOD_GENERAL_MODULEACTIVE_DESC'     => 'Diese Einstellung kontrolliert, ob dieses Modul überhaupt aktiv sein darf und Änderungen an Daten oder Verhalten hervorrufen soll.',
    'D3_CFG_MOD_GENERAL_DEBUGACTIVE'           => 'debug active',
    'D3_CFG_MOD_GENERAL_DEBUGACTIVE_DESC'      => 'Aktivieren Sie mit dem Schalter den Debugmodus. Dieser bietet im Regelfall Hilfe bei der Modulentwicklung und Fehlersuche. Welche Funktionen im Einzelnen mit dem Debugmodus zur Verfügung stehen, steht möglicherweise in der Moduldokumentation bzw. kann Ihnen der Modulautor erklären. Deaktivieren Sie den Debugmodus bitte unbedingt für den Livebetrieb.',
    'D3_CFG_MOD_GENERAL_TESTMODEACTIVE'        => 'test mode activ',
    'D3_CFG_MOD_GENERAL_TESTMODEACTIVE_DESC'   => 'Der Testmodus stellt im üblichen Sinne die Funktion des Moduls in testfähiger Version zur Verfügung. Je nach Modul kann dies sein, dass z.B. Aktionen nicht live ausgeführt werden oder andere Zugangsdaten verwendet werden. Wenden Sie sich für genauere Informationen zum Umfang des Testmodus bitte an den Modulautor. Deaktivieren Sie den Testmodus bitte unbedingt für den Livebetrieb.',
    'D3_CFG_MOD_GENERAL_MODULELOGGING'         => 'logging',
    'D3_CFG_MOD_GENERAL_MODULELOGGING_NONE'    => 'no protocoll (standard)',
    'D3_CFG_MOD_GENERAL_MODULELOGGING_ALL'     => 'log all actions ',
    'D3_CFG_MOD_GENERAL_MODULELOGGING_ERRORS'  => 'log errors only',
    'D3_CFG_MOD_GENERAL_NOCONFIG_DESC'         => 'There is no configuration available for these language.',
    'D3_CFG_MOD_GENERAL_NOCONFIG_BTN'          => 'Create configuration',
    'D3_CFG_MOD_GENERAL_SAVE'                  => 'Save',
    'D3_CFG_MOD_GENERAL_CLRTMP'                => 'Please clear the tmp folder.',

    'D3_CFG_MOD'                               => 'Support',
    'D3_CFG_MOD_VERSION'                       => 'Version',
    'D3_CFG_MOD_VERSION_TEXT1'                 => 'Module "',
    'D3_CFG_MOD_VERSION_TEXT2'                 => '", for OXID eShop',
    'D3_CFG_MOD_VERSION_INSTALLEDV'            => 'Installed module version:',
    'D3_CFG_MOD_VERSION_RESULT'                => 'Result from update check:',
    'D3_CFG_MOD_VERSION_AVAILVERSION'          => 'Available module version for your shop:',
    'D3_CFG_MOD_VERSION_NEWESTVERSION'         => 'Newest module version:',
    'D3_CFG_MOD_VERSION_NEWESTVERSION_NOTE_1'  => 'This module version is available, but it\'s not released for your used shop version. Please update your shop installation first at least to version ',
    'D3_CFG_MOD_VERSION_NEWESTVERSION_NOTE_2'  => ', to be able to use this module version.',
    'D3_CFG_MOD_VERSION_NEWESTVERSION_LIC'     => 'This module version isn\'t contained  in your licence key. Please contact us for extending your licence.',
    'D3_CFG_MOD_VERSION_MODINFO'               => 'Further informations you can see here.',
    'D3_CFG_MOD_VERSION_REV'                   => 'Rev.',
    'D3_CFG_MOD_VERSION_UPDLOAD1'              => 'You can get download this update',
    'D3_CFG_MOD_VERSION_UPDLOAD2'              => 'HERE',
    'D3_CFG_MOD_VERSION_UPDLOAD3'              => '',
    'D3_CFG_MOD_VERSION_UPDLOAD4'              => ' or ',
    'D3_CFG_MOD_VERSION_UPDLOAD5'              => 'install it automatical',
    'D3_CFG_MOD_VERSION_CHECKTXT'              => 'Check, if you use the latest release of these moduls.',
    'D3_CFG_MOD_VERSION_STARTCHECK'            => 'Check for newer release',
    'D3_CFG_MOD_VERSION_NONEWVERSION'          => 'There are no newer version for your shop available.',
    'D3_CFG_MOD_VERSION_INSTALLSTATUS'         => 'Instllation progress',

    'D3_CFG_MOD_SUPPORT'                       => 'Support',
    'D3_CFG_MOD_SUPPORT_1'                     => 'Bei Fragen oder Anregungen stehen wir Ihnen mit folgenden Kontaktmöglichkeiten gern zur Verfügung:',
    'D3_CFG_MOD_SUPPORT_2'                     => 'Phone: +49 (0)3721 268090',
    'D3_CFG_MOD_SUPPORT_3'                     => 'Fax: +49 (0)3721 265234',
    'D3_CFG_MOD_SUPPORT_4'                     => 'E-Mail:',
    'D3_CFG_MOD_SUPPORT_MAIL'                  => 'support@shopmodule.com',
    'D3_CFG_MOD_SUPPORT_5'                     => 'Die häufigsten Fragen zu diesem und anderen Modulen haben wir in unserer Online-FAQ zusammengestellt. Diese finden Sie unter <a href="http://faq.oxidmodule.de" target="_blank" alt="Modul-FAQ">http://faq.oxidmodule.de</a>.',
    'D3_CFG_MOD_SUPPORT_6'                     => 'Unsere FAQ wird ständig erweitert. Gern nehmen wir auch von Ihnen gewünschte Antworten mit auf. Schreiben Sie uns!',

    'D3_CFG_MOD_DEV'                           => 'Disclaimer',
    'D3_CFG_MOD_DEV_TEXT1'                     => 'Dieses Modul wird entwickelt und vertrieben von:',
    'D3_CFG_MOD_DEV_ADR1'                      => 'Fa. D³ Data Development',
    'D3_CFG_MOD_DEV_ADR2'                      => 'Inhaber Thomas Dartsch',
    'D3_CFG_MOD_DEV_ADR3'                      => 'Stollberger Straße 23',
    'D3_CFG_MOD_DEV_ADR4'                      => '09380 Thalheim / Erzgeb.',
    'D3_CFG_MOD_DEV_ADR5'                      => 'Deutschland',
    'D3_CFG_MOD_DEV_WEBLINK'                   => 'Homepage: <a href="http://www.shopmodule.com/" target="_blank" alt="D³ Data Development">http://www.shopmodule.com</a>',
    'D3_CFG_MOD_DEV_MAILLINK'                  => 'E-Mail:<a href="mailto:info@shopmodule.com" alt="info@shopmodule.com">info@shopmodule.com</a>',
    'D3_CFG_MOD_DEV_MODULELINK'                => 'Eine Übersicht über alle unsere Module finden Sie unter <a href="http://www.oxidmodule.de/" target="_blank" alt="D³ Data Development"><strong>http://www.oxidmodule.de</strong></a>',

    'D3_CFG_MOD_CHANGEKEY'                     => 'change licence key',
    'D3_CFG_MOD_ADDKEY'                        => 'activate licence',
    'D3_CFG_MOD_SHOWKEY'                       => 'show licence details',
    'D3_CFG_MOD_ACTIVATE'                      => 'activation',
    'D3_CFG_MOD_ACTIVATE_1'                    => 'licence key:',
    'D3_CFG_MOD_ACTIVATE_2'                    => 'save licence key',
    'D3_CFG_MOD_LICDETAILS'                    => 'license details',
    'D3_CFG_MOD_LICDETAILS_GENERALVALID'       => 'license valid:',
    'D3_CFG_MOD_LICDETAILS_VALIDDOMAIN'        => 'valid for domain:',
    'D3_CFG_MOD_LICDETAILS_VALIDLOCAL'         => 'usable in local test shop:',
    'D3_CFG_MOD_LICDETAILS_VALID_YES'          => 'yes',
    'D3_CFG_MOD_LICDETAILS_VALIDLOCAL_DESC'    => "Das Modul ist neben der lizensierten Domain auch unter der IP \"127.0.0.1\" oder \"::1\" oder der Domain \"localhost\" als Testinstallation einsetzbar. Können Sie die Möglichkeiten aus technischen Gründen nicht verwenden, richten Sie sich einfach die lizensierte Domain auf Ihrem Host ein.",
    'D3_CFG_MOD_LICDETAILS_VALIDFROMDATE'      => 'valid from:',
    'D3_CFG_MOD_LICDETAILS_VALIDTODATE'        => 'valid to:',
    'D3_CFG_MOD_LICDETAILS_VALIDFORMODID'      => 'valid for:',
    'D3_CFG_MOD_LICDETAILS_VALIDFORMODVERSION' => 'module version:',
    'D3_CFG_MOD_LICDETAILS_VALIDFORSHOPID'     => 'shop ID:',
    'D3_CFG_MOD_LICDETAILS_ISTEST'             => 'trial version:',

    'D3_CFG_MOD_TRYORBUY'                      => 'Try or buy?',
    'D3_CFG_MOD_TRYORBUY_1'                    => 'Request demo key',
    'D3_CFG_MOD_TRYORBUY_2'                    => 'Request live key',

    'D3_CFG_MOD_STAYINFORMED'                  => 'Stay informed!',
    'D3_CFG_MOD_STAYINFORMED_1'                => 'Ich möchte automatisch Informationen zu neuen Updates dieses Moduls erhalten.',
    'D3_CFG_MOD_STAYINFORMED_2'                => 'E-Mail-Adresse:',
    'D3_CFG_MOD_SAVE'                          => 'Save',

    'D3_CFG_MOD_SYS_CHECK'                     => 'System Check',
    'D3_CFG_MOD_SYS_REVOK'                     => 'Die Revisionsnummer paßt zur Shopversion.',
    'D3_CFG_MOD_SYS_REVNOK'                    => 'Die Revisionsnummer paßt nicht zur Shopversion. Bitte kontrollieren Sie dies, da die Module sich an der Revisionsnummer orientieren.',
    'D3_CFG_MOD_SYS_REVHIGHER'                 => 'Die Revisionsnummer kann aktuell nicht geprüft werden. Möglicherweise haben Sie eine neue Shopversion installiert, die noch nicht hinterlegt ist. Bitte versuchen Sie es in Kürze erneut.',
    'D3_CFG_MOD_SYS_REVUNDEF'                  => 'Die Revisionsnummer kann aktuell nicht geprüft werden. Möglicherweise ist diese Shopversion ein "nightly build".',
    'D3_CFG_MOD_SYS_CURLNOK'                   => 'Die CURL PHP Erweiterung ist nicht verfügbar. Manche Module erfordern diese. Details dazu entnehmen Sie bitte den jeweiligen Modulbeschreibungen.',
    'D3_CFG_MOD_SYS_CURLOK'                    => 'Die CURL PHP Erweiterung ist verfügbar.',
    'D3_CFG_MOD_SYS_CURLREQ'                   => 'Die CURL PHP Erweiterung ist nicht verfügbar. Dieses Modul erfordert diese jedoch zwingend. Aktivieren Sie die Erweiterung, dass das Modul fehlerfrei funktionieren kann.',
    'D3_CFG_MOD_NEWVERSION_1'                  => 'Es ist eine neue Version verfügbar: ',
    'D3_CFG_MOD_NEWVERSION_2'                  => 'Laden Sie sich diese hier herunter: ',
    'D3_CFG_MOD_NEWVERSION_3'                  => 'oder kontaktieren Sie uns für die Installation des Updates.',
    'D3_CFG_MOD_NEWVERSION_4'                  => 'Es ist keine neue Version verfügbar.',

    'D3_CFG_MOD_MODHEALTH'                     => 'Modulprüfung',
    'D3_CFG_MOD_MODHEALTH_ITEMSNOK'            => 'folgende Moduleinträge sind nicht gesetzt:',
    'D3_CFG_MOD_MODHEALTH_ITEMSOK'             => 'Moduleinträge sind vollständig gesetzt.',
    'D3_CFG_MOD_MODHEALTH_DBNOK'               => 'folgende Datenbankänderungen sind nicht gesetzt:',
    'D3_CFG_MOD_MODHEALTH_DBOK'                => 'Datenbankänderungen sind vollständig gesetzt.',
    'D3_CFG_MOD_MODHEALTH_DBTABLE'             => 'Tabelle',
    'D3_CFG_MOD_MODHEALTH_DBFIELD'             => 'Feld',
    'D3_CFG_MOD_MODHEALTH_MISSING'             => 'fehlt',
    'D3_CFG_MOD_MODHEALTH_FIELDTYPE'           => 'Fehler im Feldtyp',
    'D3_CFG_MOD_MODHEALTH_VARTYPE'             => 'Fehler im Variablentyp',
    'D3_CFG_MOD_MODHEALTH_CONTENT'             => 'fehlerhafter Inhalt',
    'D3_CFG_MOD_MODHEALTH_CONFIGNOK'           => 'folgende Konfigurationseinstellungen sind nicht oder unzureichend gesetzt:',
    'D3_CFG_MOD_MODHEALTH_CONFIGOK'            => 'Konfigurationseinstellungen sind vollständig gesetzt.',
    'D3_CFG_MOD_MODHEALTH_CONFIGNAME'          => 'Einstellung',
    'D3_CFG_MOD_MODHEALTH_SEEMANUAL'           => 'Für weitere Informationen konsultieren Sie die Installationsanleitung.',
    'D3_CFG_MOD_MODHEALTH_PROBLEM'             => 'Für das Modul wurden Installationsprobleme gefunden, die vor der Verwendung behoben werden sollten. Weitere Informationen finden Sie unter dem Support-Tab.',

    'D3_CFG_MOD_NEWS_NEWS'                     => 'Neuigkeiten und Aktuelles',
    'D3_CFG_MOD_NEWS_FURTHER1'                 => 'Diese und weitere Informationen finden Sie in unserem Oxidmodule-Blog unter',
    'D3_CFG_MOD_NEWS_FURTHER2'                 => 'Aktuelle Informationen zu uns und unseren Modulen finden Sie in unserem Oxidmodule-Blog unter',

    'D3_CFG_MODITEM_NEWITEMS'                  => 'New items',
    'D3_CFG_MODITEM_PREV'                      => '<b>Editor</b> (Klick auf den Eintrag für Optionen)',
    'D3_CFG_MODITEM_PREVIEW'                   => 'generate preview',
    'D3_CFG_MODITEM_SAVE'                      => 'save (and backup) module list',
    'D3_CFG_MODITEM_ACTIONFOR'                 => 'action for',
    'D3_CFG_MODITEM_DEACTIVE'                  => 'deactivate',
    'D3_CFG_MODITEM_DEACTIVEALLCLASS'          => 'deactivate all items of this class',
    'D3_CFG_MODITEM_ACTIVE'                    => 'activate',
    'D3_CFG_MODITEM_ACTIVEALLCLASS'            => 'activate all items of this class',
    'D3_CFG_MODITEM_ACTIVEALLMOD'              => 'activate all items of this module',
    'D3_CFG_MODITEM_DEACTIVEALLMOD'            => 'deactivate all items of this module',
    'D3_CFG_MODITEM_DELETE'                    => 'delete',
    'D3_CFG_MODITEM_DELMSG'                    => 'Soll der Moduleintrag wirklich gelöscht werden?',
    'D3_CFG_MODITEM_TOFIRST'                   => 'to front',
    'D3_CFG_MODITEM_TOLAST'                    => 'to back',
    'D3_CFG_MODITEM_CANCEL'                    => 'cancel',
    'D3_CFG_MODITEM_LEGEND'                    => 'Legend',
    'D3_CFG_MODITEM_LEGEND_EXISTS'             => 'module or class exist',
    'D3_CFG_MODITEM_LEGEND_NOTEXISTS'          => 'module or class couldn\'t loaded',
    'D3_CFG_MODITEM_LEGEND_INACTIVE'           => 'existing module or class is inactive',
    'D3_CFG_MODITEM_LEGEND_NEW'                => 'new module',
    'D3_CFG_MODITEM_LEGEND_NEWPROBLEM'         => 'new module, but has to check',

    'D3_CFG_CFGITEM_WRITEPROTECTED'            => '- write proteced',
    'D3_CFG_CFGITEM_NOTWRITEPROTECTED'         => '- not write protected',
    'D3_CFG_CFGITEM_EDITABLE'                  => '- editable ',
    'D3_CFG_CFGITEM_EDITABLE_QUESTION'         => 'CAUTION!\\n\\nChanges in this file can be harmful to the availability, functionality and security of this online shop. You should only continue if you are sure of what you are doing.',
    'D3_CFG_CFGITEM_SAVE_QUESTION'             => 'Do you really wanna save the changes?',
    'D3_CFG_CFGITEM_SAVE'                      => 'Remove write protection temporary and save',
    'D3_CFG_CFGITEM_SAVEWOPROTECTION'          => 'save file',
    'D3_CFG_CFGITEM_EDIT'                      => 'edit file',
    'D3_CFG_CFGITEM_DEMOTEXT'                  => "\r\r// Da dies ein Demoshop ist, werden Ihnen die Dateiinhalte hier nicht angezeigt.\r// Because of demoshop mode you can\'t see the file content here.",

    'D3_CFG_MAINTENANCE_MODULES'               => "Modules",
    'D3_CFG_MAINTENANCE_REPAIRMODULES'         => "repair modules database items",

    'D3_CFG_CFGLIBS_CHOOSE'                    => 'Please choose library',
    'D3_CFG_CFGLIBS_NOLIBAVAIL'                => 'no library settings available',

    'D3_CFG_MODCFG_CFG_HIDEADMINHOMEINFO'      => 'Modulinformationen auf der Admin-Startseite <b>nicht</b> zeigen',
    'D3_CFG_MODCFG_CFG_HIDEEXTSUPPORTINFO'     => 'D3 News auf Modul-Support-Seiten <b>nicht</b> zeigen',

    'SHOP_SYSTEM_MODULES'                      => 'Installierte Module in Ihrem eShop, <br>bequemes Hinzufügen / Bearbeiten im <input type="button" onclick="document.getElementById(\'myedit\').target = \'basefrm\'; document.getElementById(\'myedit\').fnc.value=\'\';document.getElementById(\'myedit\').cl.value=\'d3moditems\';document.getElementById(\'myedit\').submit();" value="Modul-Connector">',
    'D3_CFG_MSG_NONEWITEM'                     => 'Keinen neuen Moduleinträge zum Speichern vorhanden',

    'D3_MOD_LIB_METADATA_AUTHOR'               => 'D³ Data Development',
    'D3_MOD_LIB_METADATA_LOGO'                 => '<img src="../modules/_d3modcfg/public/d3logo.php" alt="D³" title="D³ Data Development">',
    'D3_MOD_LIB_METADATA_SUPPORTMAIL'          => 'support@shopmodule.com',
    'D3_MOD_LIB_METADATA_INFOURL'              => 'http://www.oxidmodule.com/',

    'D3_CFG_MOD_EXC_MODCFGNOTCALLABLE'         => 'module configuration is unavailable, because of (uncheckable) database table',
    'D3_CFG_MOD_EXC_NOMODCFGITEM'              => 'no modcfg item for this id available [<a href="http://faq.oxidmodule.com/Modul-Connector/Fehlermeldungen/keine-Modulkonfiguration-fuer-diese-ID-vorhanden.html" target="faq">more info</a>]',
    'D3_CFG_MOD_EXC_LICENSERESULT'             => 'license result is: %s [<a href="http://faq.oxidmodule.com/Modul-Connector/Fehlermeldungen/Lizenzpruefung-ergibt.html" target="faq">more info</a>]',
    'D3_CFG_MOD_EXC_NOCONFKEY'                 => 'no conf key available [<a href="http://faq.oxidmodule.com/Modul-Connector/Fehlermeldungen/keine-Basiskonfiguration-fuer-das-Modul-vorhanden.html" target="faq">more info</a>]',
    'D3_CFG_MOD_EXC_UNKNOWNCONFKEY'            => 'conf key isn\'t conform (ModId, ModVersion) [<a href="http://faq.oxidmodule.com/Modul-Connector/Fehlermeldungen/Basiskonfiguration-passt-nicht-zum-Modul-ModId-ModVersion.html" target="faq">more info</a>]',
    'D3_CFG_MOD_EXC_NOLICKEYFORCHECK'          => 'license key missing: licence activation required [<a href="http://faq.oxidmodule.com/Modul-Connector/Fehlermeldungen/fehlender-Lizenzschluessel.html" target="faq">more info</a>]',
    'D3_CFG_MOD_EXC_NOCONFKEYID'               => 'can\'t read conf key [<a href="http://faq.oxidmodule.com/Modul-Connector/Fehlermeldungen/Basiskonfiguration-kann-nicht-gelesen-werden.html" target="faq">more info</a>]',
    'D3_CFG_MOD_EXC_NOSERIALID'                => 'can\'t read licence key [<a href="http://faq.oxidmodule.com/Modul-Connector/Fehlermeldungen/Lizenzschluessel-kann-nicht-gelesen-werden.html" target="faq">more info</a>]',
    'D3_CFG_MOD_EXC_ACTIVATED'                 => 'Durch diese Aktion wurde das Modul auch gleichzeitig aktiviert. Prüfen Sie die Einstellungen im moduleigenen Konfigurationsbereich im Adminpanel Ihres Shops.',
    'D3_CFG_MOD_EXC_DEACTIVATED'               => 'Um Fehler in Ihrem Shop zu vermeiden, wurde mit dieser Aktion auch das Modul deaktiviert. Bearbeiten Sie diese Einstellung bitte immer auch im moduleigenen Konfigurationsbereich im Adminpanel Ihres Shops.',

    'D3_CFG_MOD_ACTIVATION_TYPE_HEADLINE'      => 'Dieser Assistent führt Sie durch die Modulaktivierung. Bitte wählen Sie:',
    'D3_CFG_MOD_ACTIVATION_TYPE_OXIDMODULE'    => 'Sie haben das Modul bereits im Oxidmodule.com-Shop gekauft und / oder einen Aktivierungsident vorliegen',
    'D3_CFG_MOD_ACTIVATION_TYPE_FOREIGN'       => 'Sie haben das Modul bereits bei einem anderen Anbieter gekauft (z.B. bei OXID Exchange)',
    'D3_CFG_MOD_ACTIVATION_TYPE_FOREIGN_DESC'  => 'Für alle Modulkäufe, die nicht über den Oxidmodule-Shop durchgeführt wurden, ist es erforderlich, das wir Ihren Kauf registrieren. Nur dann ist eine Aktivierung möglich.',
    'D3_CFG_MOD_ACTIVATION_TYPE_HASLICENCE'    => 'Sie haben bereits den mehrzeiligen Lizenzschlüssel vorliegen',
    'D3_CFG_MOD_ACTIVATION_TYPE_DEMO'          => 'Sie möchten das Modul kostenfrei als Testversion verwenden',
    'D3_CFG_MOD_ACTIVATION_TYPE_DEMO_DESC'     => 'Die Lizenz für die Testversion ist ab der Aktivierung 30 Tage gültig. Danach wird das Modul automatisch deaktiviert. Ihr Shop wird auch dann noch genauso wie vor der Aktivierung bedienbar sein.',
    'D3_CFG_MOD_ACTIVATION_TYPE_BUY'           => 'Sie möchten das Modul kaufen',
    'D3_CFG_MOD_ACTIVATION_TYPE_BUY_DESC'      => 'Sie werden direkt in unseren Modulshop weitergeleitet. Im Shop sehen Sie Details zu diesem Modul und können es auch erwerben. Mit sofort buchbaren Zahlarten (z.B. Paypal oder Kreditkarte) erhalten Sie direkt im Anschluss den Aktivierungsident.',
    'D3_CFG_MOD_ACTIVATION_TYPE_NOTLISTED'     => 'Ihre gewünschte Aktion ist hier nicht aufgeführt',
    'D3_CFG_MOD_ACTIVATION_DATA_HEADLINE'      => 'Für die Aktivierung werden folgende Daten verwendet und übertragen:',
    'D3_CFG_MOD_ACTIVATION_DATA_MODULE'        => 'Modul:',
    'D3_CFG_MOD_ACTIVATION_DATA_MODULE_DESC'   => 'Das Modul wird fest in der zukünftigen Lizenz vermerkt. Verwenden Sie daher bitte auch nur den Aktivierungsident des dazu gehörenden Moduls. Beachten Sie, dass Ihr Modulkauf auch für die richtige Shopedition erfolgt sein muss. Andernfalls können Sie dieses Modul nicht aktivieren. Möchten Sie die Aktivierung für ein anderes Modul durchführen, verlassen Sie bitte diesen Assistent und rufen diesen in dem zu aktivierenden Modul auf.',
    'D3_CFG_MOD_ACTIVATION_DATA_MODVERSION'    => 'Modulversion:',
    'D3_CFG_MOD_ACTIVATION_DATA_MODVERSION_DESC'=> 'Die Modulversion wird fest in der zukünftigen Lizenz vermerkt. Neben dem Ablaufdatum entscheidet die Modulversion, welche zukünftigen Updates / Upgrades Sie mit dieser Lizenz verwenden können. Planen Sie kurzfristig eine Modulaktualisierung, klären Sie bitte mit uns die Vorgehensweise.',
    'D3_CFG_MOD_ACTIVATION_DATA_DOMAIN'        => 'Domain:',
    'D3_CFG_MOD_ACTIVATION_DATA_DOMAIN_DESC'   => 'Die Domain wird fest in der zukünftigen Lizenz vermerkt. Ausschlag gebend ist hier die Shophauptdomain, die in der Konfigurationsdatei des Shops eingetragen ist. Sprach- und mandantenabhängige Domains sowie Subdomains werden bei der Lizenz nicht berücksichtigt. Möchten Sie dieses Modul in einem Shop unter einer anderen Domain einsetzen, führen Sie dessen Aktivierung bitte nur dort durch.',
    'D3_CFG_MOD_ACTIVATION_DATA_SHOP'          => 'Shop-Mandant:',
    'D3_CFG_MOD_ACTIVATION_DATA_SHOP_DESC'     => 'Der Shopmandant wird fest in der zukünftigen Lizenz vermerkt. Der Shoptitel wird für Sie nur informatorisch angezeigt. <br>Für Shopinhaber der Enterprise-Edition: Möchten Sie dieses Modul für einen anderen Mandanten aktivieren, wechseln Sie diesen bitte und führen Sie die Aktivierung bitte nur dort durch.',
    'D3_CFG_MOD_ACTIVATION_DATA_EDITION'       => 'Shop-Edition:',
    'D3_CFG_MOD_ACTIVATION_DATA_EDITION_DESC'  => 'Die Shop-Edition benötigen wir, um das richtige Modul zu Ihrer Aktivierung zuordnen zu können.',
    'D3_CFG_MOD_ACTIVATION_DATA_VOUCHER'       => 'Aktivierungsident:',
    'D3_CFG_MOD_ACTIVATION_DATA_VOUCHER_DESC'  => 'Den Ident erhalten Sie von uns beim Kauf Ihres Moduls in unserem Shop oder bei manueller Registrierung und besteht aus 32 Zeichen. Er sagt nur aus, dass Sie dieses Modul erworben haben. Daran ist jedoch noch kein Shop gebunden. Erst durch die Aktivierung wird dieser Kauf auf Ihren Shop fixiert.',
    'D3_CFG_MOD_ACTIVATION_DATA_DEMO_DESC'     => 'Diese hier erstellte Testlizenz ist maximal 30 Tage gültig. Danach wird das Modul automatisch deaktiviert. Ihr Shop wird auch dann noch genauso wie vor der Aktivierung bedienbar sein.',
    'D3_CFG_MOD_ACTIVATION_FOREIGN_HEADLINE'   => 'Kontaktieren Sie uns bitte...',
    'D3_CFG_MOD_ACTIVATION_FOREIGN_DESC'       => 'Senden Sie uns bitte Ihren Kaufbeleg. (Unsere Kontaktdaten finden Sie im oben stehenden "Support"-Tab.) Sie erhalten dann von uns den Ident, mit dem Sie Ihr Modul über diesen Assistenten aktivieren können. Haben Sie den Ident schon vorliegen, wählen Sie in der folgenden Auswahl den ersten Punkt.',
    'D3_CFG_MOD_ACTIVATION_HASSERIAL_HEADLINE' => 'Tragen Sie bitte hier Ihren Lizenzschlüssel ein:',
    'D3_CFG_MOD_ACTIVATION_BUY_HEADLINE'       => 'Sie haben sich für dieses Modul entschieden?',
    'D3_CFG_MOD_ACTIVATION_BUY_DESC_1'         => 'Über den folgenden Link kommen Sie in unseren Shop, in dem Sie das Modul bestellen können. Bei Auswahl einer sofort buchbaren Zahlart (z.B. Paypal oder Kreditkarte) erhalten Sie direkt im Anschluss den Aktivierungsident, mit dem Sie die Aktivierung fertigstellen können.<p style="text-align: center;"><a href="',
    'D3_CFG_MOD_ACTIVATION_BUY_DESC_2'         => '" style="font-weight: bold; text-decoration: underline;" target="oxidmodule">Oxidmodule Shop</a></p> Vielen Dank für Ihre Bestellung. Haben Sie mit dem Bestellabschluss einen Aktivierungsident erhalten, wählen Sie zum Abschluss in der folgenden Auswahl den ersten Punkt.',
    'D3_CFG_MOD_ACTIVATION_NOTLISTED_HEADLINE' => 'Kontaktieren Sie uns bitte...',
    'D3_CFG_MOD_ACTIVATION_NOTLISTED_DESC'     => 'Unsere Kontaktdaten finden Sie im oben stehenden "Support"-Tab. Wir nehmen uns Ihrer Anfrage gern persönlich an. <br>Sind wir möglicherweise gerade nicht erreichbar, hilft es Ihnen vielleicht, das Modul vorab als Testversion zu aktivieren.',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_NEXT'        => 'Weiter',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_ACTNOW'      => 'Modul jetzt aktivieren',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_BACK'        => 'Zurück zur Übersicht',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_SERIAL'      => 'Lizenzschlüssel jetzt austauschen',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_SETDEMO'     => 'Testversion jetzt aktivieren',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_SUCCESS_HL'  => 'Die Aktivierung wurde erfolgreich durchgeführt.',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_SUCCESS_NOEXP' => 'Die Modullizenz ist unbegrenzt ',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_SUCCESS_1'   => 'Die Modullizenz ist bis zum ',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_SUCCESS_2'   => ' gültig und wurde schon am Modul hinterlegt. Kopieren Sie sich den Lizenzschlüssel bitte für Ihre Unterlagen. Wir wünschen Ihnen mit dem Modul viel Erfolg.',
    'D3_CFG_MOD_ACTIVATION_SUBMIT_NSUCCESS_HL' => 'Die Aktivierung konnte leider nicht durchgeführt werden.',
    'D3_CFG_MOD_ACTIVATION_ERRMISSINGPARAMS'   => 'Der Lizenzschlüssel kann wegen fehlender Informationen nicht abgerufen werden. Kontaktieren Sie uns bitte. Unsere Kontaktdaten finden Sie im oben stehenden "Support"-Tab.',
    'D3_CFG_MOD_ACTIVATION_ERRUNKNOWNMODULE'   => 'Das Modul ist in dieser Version (noch) nicht aktivierbar. Kontaktieren Sie uns bitte. Unsere Kontaktdaten finden Sie im oben stehenden "Support"-Tab.',
    'D3_CFG_MOD_ACTIVATION_ERRTOMUCHTESTLIC'   => 'Für dieses Modul wurden in diesem Shop schon Testversionen erstellt. Für eine erneuten Modultest kontaktieren Sie uns bitte. Unsere Kontaktdaten finden Sie im oben stehenden "Support"-Tab.',
    'D3_CFG_MOD_ACTIVATION_ERRNOORDER'         => 'Zu Ihrem Aktivierungsident konnte keine passende Bestellung oder kein passendes Modul gefunden werden. Aktivieren Sie das Modul bitte ausschließlich mit dem dazugehörigen Ident.',
    'D3_CFG_MOD_ACTIVATION_ERRWRONGEDITION'    => 'Das erworbene Modul kann unter dieser Shopedition nicht aktiviert und betrieben werden. Kontaktieren Sie uns bitte.',
    'D3_CFG_MOD_ACTIVATION_ERRDIFFERENTSHOPS'  => 'Für das Modul erhielten Sie mehrere Aktivierungsidents. Diese sind zum Beispiel für verschiedene Mandanten nötig. Einer dieser Idents wurde schon in einer anderen Shopinstallation aktiviert. Möchten Sie dieses Modul in unterschiedlichen Shops einsetzen, kontaktieren Sie uns bitte.',
    'D3_CFG_MOD_ACTIVATION_SAVESERIALSUCC'     => 'Der Lizenzschlüssel wurde erfolgreich eingetragen. Wir wünschen Ihnen mit dem Modul viel Erfolg.',

    'D3_CFG_MOD_NOTACTIVE'                     => 'Das Modul ist nicht aktiv. Prüfen Sie die Einstellungen in der Modulverwaltung.',

    'D3_CFG_MOD_STATUS_OK'                     => 'This licence key is valid.',
    'D3_CFG_MOD_STATUS_TMINUS'                 => 'Die Lizenz ist erst zukünftig gültig.',
    'D3_CFG_MOD_STATUS_EXPIRED'                => 'This licence has expired.',
    'D3_CFG_MOD_STATUS_EXPIRES_IN'             => 'This licence key expires in %s.',
    'D3_CFG_MOD_STATUS_NEVER_EXPIRES'          => 'This licence doesn\'t expires.',
    'D3_CFG_MOD_STATUS_ILLEGAL'                => 'This licence isn\'t valid. Maybe it was created for another dowain.',
    'D3_CFG_MOD_STATUS_ILLEGAL_LOCAL'          => 'This licence was not created for local use.',
    'D3_CFG_MOD_STATUS_ILLEGAL_INVALID'        => 'This licence key isn\'t readable.',
    'D3_CFG_MOD_STATUS_WRONG_MODULE'           => 'Die Lizenz ist nicht für dieses Modul vorgesehen.',
    'D3_CFG_MOD_STATUS_WRONG_MODVERSION'       => 'Die Lizenz ist nicht für diese Modulversion vorgesehen.',
    'D3_CFG_MOD_STATUS_WRONG_SHOPID'           => 'Die Lizenz ist nicht für diesen Shopmandanten aktiviert.',
    'D3_CFG_MOD_STATUS_EMPTY'                  => 'Die Lizenz enthält keine Informationen.',
    'D3_CFG_MOD_STATUS_CORRUPT'                => 'Die Lizenz wurde nicht vom authentifizierten Autor erstellt.',
    'D3_CFG_MOD_STATUS_404'                    => 'Die Lizenz ist nicht vorhanden.',

    'D3_CFG_MOD_NEVER'                         => 'never',
    'D3_CFG_MOD_SECOND'                        => 'second',
    'D3_CFG_MOD_SECONDS'                       => 'seconds',
    'D3_CFG_MOD_MINUTE'                        => 'minute',
    'D3_CFG_MOD_MINUTES'                       => 'minutes',
    'D3_CFG_MOD_HOUR'                          => 'hour',
    'D3_CFG_MOD_HOURS'                         => 'hours',
    'D3_CFG_MOD_DAY'                           => 'day',
    'D3_CFG_MOD_DAYS'                          => 'days',
    'D3_CFG_MOD_MONTH'                         => 'month',
    'D3_CFG_MOD_MONTHS'                        => 'months',
    'D3_CFG_MOD_YEAR'                          => 'year',
    'D3_CFG_MOD_YEARS'                         => 'years',

    'D3_MODPROFILE_MAIN_ACTIVE'                => 'active',
    'D3_MODPROFILE_MAIN_ACTIVE_DESC'           => '',
    'D3_MODPROFILE_MAIN_ACTIVFROMTILL'         => 'or active',
    'D3_MODPROFILE_MAIN_ACTIVEFROM'            => 'from',
    'D3_MODPROFILE_MAIN_ACTIVETO'              => 'to',
    'D3_MODPROFILE_MAIN_TITLE'                 => 'title',
    'D3_MODPROFILE_MAIN_NOFOLDER'              => 'no folder selected',
    'D3_GENERAL_MODPROFILE_TITLE'              => 'title',
    'D3_GENERAL_MODPROFILE_SORT'               => 'sort',
    'D3_GENERAL_MODPROFILE_SAVE'               => 'save',
    'D3_GENERAL_MODPROFILE_COPY'               => 'create identical copy',
    'D3_GENERAL_MODPROFILE_EXPORT'             => 'export profile as SQL',
    'D3_MODPROFILE_MAIN_SORT'                  => 'sort',
    'D3_MODPROFILE_MAIN_FOLDER'                => 'folder',
    'D3_MODPROFILE_FOLDER_ALL'                 => 'no folder selected',
    'D3_GENERAL_MODPROFILE_COPY_PREFIX'        => 'copy from ',
);