[{if $tree}]
[{defun name="category_options" list=$tree sSpacer=""}]
    [{foreach from=$list item=ocat}]
        [{if 0==$ocat->oxcategories__trotype->value && $ocat->getIsVisible()}]
[{*** D3 Modul "extSearch" CHANGE START }]
		    <option value="[{$ocat->oxcategories__oxid->value}]"[{if $searchcnid == $ocat->oxcategories__oxid->value && !$isextsearch}] selected[{/if}]>[{$sSpacer}][{ $ocat->oxcategories__oxtitle->value }][{ if $ocat->getNrOfArticles() > 0 }] ([{$ocat->getNrOfArticles()}])[{/if}]</option>
[{*** D3 Modul "extSearch" CHANGE END ***}]
                [{fun name="category_options" list=$ocat->getSubCats() sSpacer="-$sSpacer "}]
        [{/if}]
    [{/foreach}]
[{/defun}]
[{/if}]
