<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * http://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
//Navigation
    'charset'                                          => 'ISO-8859-15',
    'D3_INSTALL'                                       => 'Installation',

    'D3INSTALL_LIB_TRANSL'                             => 'Automatic Installation',

    'D3_INSTALL_SETUPSTEPS_INIT'                       => 'start installation',
    'D3_INSTALL_PROGRESS'                              => 'progess: ',

    'D3_INSTALL_STARTSETUP'                            => 'Create a backup of you database before the installation start, so that you can restore it in case of error. <br>File backups will create by the installation automaticly.',
    'D3_INSTALL_STARTSETUP1'                           => 'May you start the installation of "',
    'D3_INSTALL_STARTSETUP2'                           => '"?',
    'D3_INSTALL_SETUPCOUNT'                            => 'Update step %s',
    'D3_INSTALL_SETUPSTEPS'                            => 'The following steps will executed:',
    'D3_INSTALL_SETUPSTEPS_GETARCHIVE'                 => 'module package will downloaded',
    'D3_INSTALL_SETUPSTEPS_LOADDESC'                   => 'module package will downloaded and extracted',
    'D3_INSTALL_SETUPSTEPS_EXTRACTARCHIVE'             => 'module package will extracted',
    'D3_INSTALL_SETUPSTEPS_CHECKDEPENDENCIES'          => 'dependensies found',
    'D3_INSTALL_SETUPSTEPS_SHOWDESCRIPTION'            => 'Description',
    'D3_INSTALL_SETUPSTEPS_COPYFILES'                  => 'files will copied (and backuped, if required) ',
    'D3_INSTALL_SETUPSTEPS_COPYFILES_DESC'             => 'All files inside the "copy_this" directory will copied into the shop, existing files will backuped.',
    'D3_INSTALL_SETUPSTEPS_COPYFILES_SOURCEPATH'       => 'source path',
    'D3_INSTALL_SETUPSTEPS_COPYFILES_DESTPATH'         => 'target path',
    'D3_INSTALL_SETUPSTEPS_MODSTEPS'                   => 'module items will written (module related)',
    'D3_INSTALL_SETUPSTEPS_DBITEMS'                    => 'database item will inserted (module related)',
    'D3_INSTALL_SETUPSTEPS_ACTUALIZE'                  => 'refresh system',
    'D3_INSTALL_SETUPSTEPS_GETUSERDATA'                => 'request required data',
    'D3_INSTALL_SETUPSTEPS_SAVEDATA'                   => 'save required data',
    'D3_INSTALL_SETUPSTEPS_SETUSERDATA'                => 'save data',
    'D3_INSTALL_SETUPSTEPS_REGISTERMODULE'             => 'register module',
    'D3_INSTALL_SETUPSTEPS_REGISTERMODULE_DESC'        => 'Folgende Moduleinträge sollen gesetzt werden. An schon existierende Erweiterungen müssen die neuen Einträge angehängt werden.',
    'D3_INSTALL_SETUPSTEPS_REGISTERMODULE_NOITEMS'     => 'no new modul items available',
    'D3_INSTALL_SETUPSTEPS_REGISTEROXUTILS'            => 'register utils module',
    'D3_INSTALL_SETUPSTEPS_REGISTEROXUTILS_DESC'       => 'Das folgende Utils-Modulist zu registrieren. Tragen Sie dies ggf. im Adminbereich im Feld unterhalb der Module ein.',
    'D3_INSTALL_SETUPSTEPS_REGISTEROXUTILS_NOITEMS'    => 'no new utils itkems available',
    'D3_INSTALL_SETUPSTEPS_EXECUTESQL'                 => 'execute database changes',
    'D3_INSTALL_SETUPSTEPS_EXECUTESQL_DESC'            => 'Folowing queries will executed in database:',
    'D3_INSTALL_SETUPSTEPS_EXECUTESQL_NOITEMS'         => 'no queries to execute available',
    'D3_INSTALL_SETUPSTEPS_REGISTERCONFIGVAR'          => 'set configuration settings',
    'D3_INSTALL_SETUPSTEPS_SETDATA'                    => ' - Verarbeitung',
    'D3_INSTALL_SETUPSTEPS_FINISHED'                   => 'installation finished',
    'D3_INSTALL_SETUPSTEPS_FINISHED_DESC'              => 'Die Modulinstallation konnte erfolgreich beendet werden.',
    'D3_INSTALL_SETUPSTEPS_FINISHED_DESC2'             => 'Wir wünschen Ihnen viel Erfolg!',
    'D3_INSTALL_CLEANUP'                               => 'Nach der Installation muß das TMP-Verzeichnis geleert werden. Soll dies nun durchgeführt werden?',
    'D3_INSTALL_CLEANUPSTART'                          => 'clear TMP folder now',
    'D3_INSTALL_CLEANUPSUCCESS'                        => 'The TMP folder was cleared successfull.',
    'D3_INSTALL_CLEANUPNOTSUCCESS'                     => 'Das TMP-Verzeichnis konnte nicht (komplett) geleert werden. Bitte führe Sie dies noch einmal selbst durch.',
    'D3_INSTALL_PROTOKOLLURI'                          => 'Das folgende Installationprotokoll ist ebenfalls auf Ihrem Server abgelegt: ',
    'D3_INSTALL_YES'                                   => 'automatic installation*',
    'D3_INSTALL_YESEXPERT'                             => 'user defined installation*',
    'D3_INSTALL_NO'                                    => 'cancel',
    'D3_INSTALL_SETUPDESC'                             => '* Die Expressinstalltion läuft komplett automatisiert ab. <br>Bei der "benutzerdefinierte Installation" können Sie auch einzelne Schritte überspringen und ggf. manuell durchführen. Dies empfiehlt sich für stark angepaßte Shops.',
    'D3_INSTALL_SETUPSTEPS_ERROR'                      => 'error occured while installation',
    'D3_INSTALL_EXPMODEQUESTION'                       => 'Soll der Schritt automatisch ausgeführt werden oder wollen Sie mit dem nächsten Punkt fortsetzen (die Aktion sollte dann manuell durchgeführt werden)?',
    'D3_INSTALL_EXPMODEEXECAUTO'                       => 'execute it automatic',
    'D3_INSTALL_EXPMODENXTSTEP'                        => 'continue with next step',
    'D3_INSTALL_NONEXISTINGSTEP'                       => 'Die erwartete Updatefunktion steht leider nicht zur Verfügung. Ist ein Update der "Install"-Bibliothek verfügbar, installieren Sie dies bitte vorher. Versuchen Sie diese Installation dann erneut.',
    'D3_INSTALL_SETUPSTEPS_DESCCONTINUE'               => 'continue installation',
    'D3_INSTALL_DEPENDENCIES_POSSUPDATE'               => 'Diese Bibliothek / Modul erfordert, dass zuvor eine andere Bibiothek in einer bestimmten Version installiert ist. Wahrscheinlich sind Funktionen daraus zwingend erforderlich. Installieren Sie die folgenden Bibliotheken, bevor Sie diese Installation fortsetzen:',
    'D3_INSTALL_DEPENDENCIES_REQUNEWINSTALL'           => 'Die verfügbaren Bibliotheken können auf Grund gegenseitiger Abhängigkeiten nicht aktualisiert werden. Bitte installieren Sie die "Erstinstallation" neu. Dieses Paket können Sie in unserem Shop kostenfrei laden.',
    'D3_INSTALL_DEPENDENCIES_NOINSTALLPOSS'            => 'Die Installation erfordert Bibliotheken, die aktuell nicht zur Verfügung stehen. Bitte kontaktieren Sie uns für weitere Unterstützung.',
    'D3_INSTALL_DEPENDENCIES_UNDEFERROR'               => 'Unbekannte Abhängigkeit: Bitte versuchen Sie, die Installations-Bibliothek zuerst zu aktualisieren. Alternativ verwenden Sie bitte das "Erstinstallationspaket" von unserer Seite oxidmodule.com für die Installation.',
    'D3_INSTALL_DEPENDENCIES_MINREV'                   => 'minimum in revision',
    'D3_INSTALL_DEPENDENCIES_MINVERSION'               => 'minimum in version',
    'D3_INSTALL_DEPENDENCIES_STARTINSTALL'             => '- start installation',
    'D3_INSTALL_SETUPSTEPS_IGNORE'                     => 'continue anyhow',
    'D3_INSTALL_ROLLBACK1'                             => 'Während der Installation konnte eine Aktion nicht erfolgreich ausgeführt werden.<br><br>Das ist aber kein Problem. An welcher Stelle die Installation abgebrochen wurde, entnehmen Sie bitte den unten gezeigten Protokolleinträgen.',
    'D3_INSTALL_ROLLBACK2'                             => 'Sie haben die Wahl:',
    'D3_INSTALL_ROLLBACK3'                             => 'Sie führen die Installation ab diesem Punkt selbst zu Ende, dann brechen Sie hier bitte ab.',
    'D3_INSTALL_ROLLBACK5'                             => 'Das Modul können Sie hier laden.',
    'D3_INSTALL_ROLLBACK4'                             => 'Die bisherige Installation wird rückgängig gemacht, um einen neuen Versuch (manuell) zu starten',
    'D3_INSTALL_SETUPSTEPS_INITROLLBACK'               => 'Installation rückgängig machen',
    'D3_INSTALL_ROLLBACKCANCEL'                        => 'cancel installation',
    'D3_INSTALL_SETUPSTEPS_ROLLBACK_REGISTERCONFIGVAR' => 'Konfigurationseinstellungen zurücksetzen',
    'D3_INSTALL_SETUPSTEPS_ROLLBACK_EXECUTESQL'        => 'Datenbankeinträge können nicht zurückgesetzt',
    'D3_INSTALL_SETUPSTEPS_ROLLBACK_REGISTEROXUTILS'   => 'reset utils module items',
    'D3_INSTALL_SETUPSTEPS_ROLLBACK_REGISTERMODULE'    => 'reset module items',
    'D3_INSTALL_SETUPSTEPS_ROLLBACK_GETUSERDATA'       => 'reset user settings',
    'D3_INSTALL_SETUPSTEPS_ROLLBACK_COPYFILES'         => 'reset files',
    'D3_INSTALL_SETUPSTEPS_ROLLBACK_END'               => 'rollback finished',
    'D3_INSTALL_PROTOKOLL_SUCCESSFULL'                 => 'successfull',
    'D3_INSTALL_FINISH'                                => 'finish installation',
    'D3_INSTALL_PROTOKOLL_NOTSUCCESSFULL'              => 'error',
    'D3_INSTALL_FTPINFO_DISABLED'                      => 'Bricht die Installation wegen mangelnder Rechte ab, versuchen Sie den Transfer über ein FTP-Konto.<br>Konfigurieren Sie die Einstellungen unter [D3 Module] -> [Systemeinstellungen] -> [Bibliothekseinstellungen] -> [Installationsautomatik].',
    'D3_INSTALL_FTPINFO_ENABLED'                       => 'Sie verwenden den FTP-Modus. Dateioperationen benötigen dadurch deutlich mehr Zeit.<br>Konfigurieren Sie die Einstellungen unter [D3 Module] -> [Systemeinstellungen] -> [Bibliothekseinstellungen] -> [Installationsautomatik].',
    'D3_INSTALL_FTPINFO_CONFIG'                        => 'Aktivieren Sie den FTP-Modus, wenn Bibliotheksupdates wegen mangelnder Rechte nicht ausgeführt werden können. Beachten Sie bitte, dass Dateioperationen dadurch deutlich mehr Zeit benötigen. Bevorzugen Sie nach Möglichkeit die Installation ohne FTP-Modus.',

    'D3_INSTALL_PROTOKOLLITEM_ACR'                     => 'rollback: system refreshed',
    'D3_INSTALL_PROTOKOLLITEM_ACT'                     => 'system refreshed',
    'D3_INSTALL_PROTOKOLLITEM_RMR'                     => 'rollback: module meta informations refreshed',
    'D3_INSTALL_PROTOKOLLITEM_RMM'                     => 'module meta informations refreshed',
    'D3_INSTALL_PROTOKOLLITEM_ARC'                     => 'error while downloading the archive',
    'D3_INSTALL_PROTOKOLLITEM_ARG'                     => 'archive downloaded',
    'D3_INSTALL_PROTOKOLLITEM_BFE'                     => 'unable to archive file',
    'D3_INSTALL_PROTOKOLLITEM_CDE'                     => 'unable to create directory',
    'D3_INSTALL_PROTOKOLLITEM_CFD'                     => 'unable to create directory',
    'D3_INSTALL_PROTOKOLLITEM_CFE'                     => 'no files to copy, is archive possible empty?',
    'D3_INSTALL_PROTOKOLLITEM_CFR'                     => 'files were overwritten, backup coies were created',
    'D3_INSTALL_PROTOKOLLITEM_CFG'                     => 'files were copied',
    'D3_INSTALL_PROTOKOLLITEM_CFM'                     => 'file permissions couldn\'t changed',
    'D3_INSTALL_PROTOKOLLITEM_CFN'                     => 'file couldn\'t copied',
    'D3_INSTALL_PROTOKOLLITEM_CLE'                     => 'TMP folder couldn\'t cleared, please clear it manually',
    'D3_INSTALL_PROTOKOLLITEM_CLT'                     => 'clear TMP folder',
    'D3_INSTALL_PROTOKOLLITEM_CNE'                     => 'Curl request isn\'t executable',
    'D3_INSTALL_PROTOKOLLITEM_DNC'                     => 'directory couldn\'t created: %s',
    'D3_INSTALL_PROTOKOLLITEM_DNC_E'                   => 'Could not create dir <b>%s</b>, please create it manually.<br>For further informations see <a href="http://faq.oxidmodule.de/">http://faq.oxidmodule.de/</a>',
    'D3_INSTALL_PROTOKOLLITEM_DND'                     => 'directory couldn\'t deleted: %s',
    'D3_INSTALL_PROTOKOLLITEM_DNM_E'                   => 'Unable to set write permissions for <b>%s</b>, please configure it manually.<br>For further informations see <a href="http://faq.oxidmodule.de/">http://faq.oxidmodule.de/</a>',
    'D3_INSTALL_PROTOKOLLITEM_DNO'                     => 'unable to read directory: %s',
    'D3_INSTALL_PROTOKOLLITEM_FCF'                     => 'unable to copy element: %s',
    'D3_INSTALL_PROTOKOLLITEM_FCG'                     => 'Gruppenzuordnung kann nicht geändert werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_FCM'                     => 'Berechtigungen können nicht gesetzt werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_FCO'                     => 'Owner kann nicht geändert werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_FGG'                     => 'Gruppenzuordnung kann nicht ermittelt werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_FGO'                     => 'Owner kann nicht ermittelt werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_FNC'                     => 'Datei kann nicht geöffnet oder erstellt werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_FND'                     => 'Datei kann nicht gelöscht werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_FNP'                     => 'Dateizugriffsrechte können nicht gelesen werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_FNR'                     => 'Datei kann nicht gelesen werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_FNW'                     => 'Datei kann nicht beschrieben werden oder kein Inhalt vorhanden.',
    'D3_INSTALL_PROTOKOLLITEM_FXS'                     => 'file doesn\'t exist: %s',
    'D3_INSTALL_PROTOKOLLITEM_RAG'                     => 'module archive saved',
    'D3_INSTALL_PROTOKOLLITEM_RFE'                     => 'Wiederherstellen: keine Dateien für Restore gefunden',
    'D3_INSTALL_PROTOKOLLITEM_RFG'                     => 'Wiederherstellen: Dateien wurden zurückkopiert',
    'D3_INSTALL_PROTOKOLLITEM_RMG'                     => 'Module registriert',
    'D3_INSTALL_PROTOKOLLITEM_RMI'                     => 'Modul registriert',
    'D3_INSTALL_PROTOKOLLITEM_ROG'                     => 'oxutils-Modul registriert',
    'D3_INSTALL_PROTOKOLLITEM_RUG'                     => 'Wiederherstellen: oxutils-Modul zurückgeschrieben',
    'D3_INSTALL_PROTOKOLLITEM_RUE'                     => 'Wiederherstellen: oxutils-Modul konnten nicht zurückgeschrieben werden, Sicherung liegt vor',
    'D3_INSTALL_PROTOKOLLITEM_RRE'                     => 'Wiederherstellen: Moduleinträge konnten nicht zurückgeschrieben werden, Sicherung liegt vor',
    'D3_INSTALL_PROTOKOLLITEM_RRG'                     => 'Wiederherstellen: Moduleinträge zurückgeschrieben',
    'D3_INSTALL_PROTOKOLLITEM_SNE'                     => 'Systembefehl kann nicht ausgeführt werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_SQE'                     => 'Datenbankeintrag gesetzt',
    'D3_INSTALL_PROTOKOLLITEM_SQL'                     => 'Datenbankeinträge gesetzt',
    'D3_INSTALL_PROTOKOLLITEM_SQR'                     => 'Wiederherstellen: Datenbank nicht wiederherstellbar, bitte ggf. eigene Sicherung wiederherstellen',
    'D3_INSTALL_PROTOKOLLITEM_SVG'                     => 'Benutzereingaben gespeichert',
    'D3_INSTALL_PROTOKOLLITEM_XAN'                     => 'Archiv entpacken, kein Archiv gefunden',
    'D3_INSTALL_PROTOKOLLITEM_XAO'                     => 'archive extracted',
    'D3_INSTALL_PROTOKOLLITEM_XAS'                     => 'archive extracted',
    'D3_INSTALL_PROTOKOLLITEM_XNP'                     => 'unable to read XML',
    'D3_INSTALL_PROTOKOLLITEM_ZNF'                     => 'Größe der gepackten Datei kann nicht ermittelt werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_ZNN'                     => 'Name der gepackten Datei kann nicht ermittelt werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_ZNO'                     => 'gepackte Datei %s kann nicht geöffnet werden: %s',
    'D3_INSTALL_PROTOKOLLITEM_ZNR'                     => 'gepackte Datei kann nicht gelesen werden: %s',
    'D3_INSTALL_PROTOKOLL_SUCCESS'                     => 'installation will successfully finished',
    'D3_INSTALL_PROTOKOLL_ERROR'                       => 'Während der Installation sind Fehler auftreten',
    'D3_INSTALL_PROTOKOLL_DETAILS'                     => '&nbsp;-&nbsp;click for details',

    'D3_INSTALL_CFG_FORCEFTP'                          => 'FTP-Verbindung zum Kopieren von Dateien verwenden',
    'D3_INSTALL_CFG_FORCEFTP_HELP'                     => 'Die zu verwendende FTP-Verbindung muss über ausreichend Berechtigungen zum Löschen und Anlegen von Dateien verfügen.',
    'D3_INSTALL_CFG_FTPSERVER'                         => 'FTP-Servername',
    'D3_INSTALL_CFG_FTPPORT'                           => 'FTP-Port (optional)',
    'D3_INSTALL_CFG_FTPPATH'                           => 'Pfad zum Shoprootverzeichnis',
    'D3_INSTALL_CFG_FTPUSER'                           => 'FTP-Benutzername',
    'D3_INSTALL_CFG_FTPPASS'                           => 'FTP-Passwort (nur, wenn benötigt)',
    'D3_INSTALL_CFG_SAVE'                              => 'speichern',

    'D3_UPDATE_AVAILABLE_VERSION'                      => '<span style="margin: 10px;"><img src="../modules/_d3modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> <a href="%s" target="modupdate">New module version for "%s" (version %s) available.</a></span>',
    'D3_UPDATE_AVAILABLE_VERSION_NOLINK'               => '<span style="margin: 10px;"><img src="../modules/_d3modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> New module version for "%s" (version %s) available.</span>',
    'D3_UPDATE_REQUIRED_MODCFGUPDATE'                  => '<span style="margin: 10px;"><img src="../modules/_d3modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> <a href="%s" taregt="basefrm" style="color: red; font-weight: bold;">Module connector requires an important installation. Click here to start the installation wizzard.</a></span>',

    'D3_CFG_MOD_UPDATE_TITLE'                          => 'D³ Modul-Installationsassistent',
    'D3_CFG_MOD_UPDATE_DESC'                           => 'Statt der von Ihnen gewählten Ansicht sehen Sie hier den Modul-Installationsassistenten. Dieser wird gezeigt, da eines oder mehrere Ihrer D³ Module für deren ordnungsgemäße Funktion einige Einstellungen am Shop vornehmen müssen.',
    'D3_CFG_MOD_UPDATE_SELECTDESC'                     => 'Der Installationsassistent wird gezeigt, da eines oder mehrere Ihrer D³ Module für deren ordnungsgemäße Funktion einige Einstellungen am Shop vornehmen müssen.',
    'D3_CFG_MOD_UPDATE_START'                          => 'Start',
    'D3_CFG_MOD_UPDATE_CHOOSESTEP'                     => 'Wählen Sie, wie Sie fortsetzen möchten:',
    'D3_CFG_MOD_UPDATE_DEMOSHOP'                       => 'Da dieser Shop im Demo-Modus läuft, sind nicht alle Optionen auswählbar. Wenden Sie sich dazu bitte an den technischen Betreuer.',
    'D3_CFG_MOD_UPDATE_STEP_AUTOINSTALL'               => 'Updates automtisch installieren',
    'D3_CFG_MOD_UPDATE_STEP_AUTOINSTALL_DESC'          => 'Die erforderlichen Installationen werden automatisch mit den Standardoptionen ausgeführt. Alle Aktionen werden protokolliert. <br><b>Diese Option ist für die meisten Shops empfohlen.</b>',
    'D3_CFG_MOD_UPDATE_STEP_MANUALYINSTALL'            => 'Updates mit Rückfrage bei jeder Aktion installieren',
    'D3_CFG_MOD_UPDATE_STEP_MANUALYINSTALL_DESC'       => 'Die erforderlichen Installationen werden ausgeführt. Vor jedem Installationsschritt entscheiden Sie, ob dieser wirklich ausgeführt werden soll. <br><b>Diese Option ist für eher ungewöhnliche Servereinrichtungen empfohlen.</b>',
    'D3_CFG_MOD_UPDATE_STEP_CHECKLIST'                 => 'eine Liste für manuelle Installation erstellen',
    'D3_CFG_MOD_UPDATE_STEP_CHECKLIST_DESC'            => 'Der Installationsassistent erstellt Ihnen eine Liste mit den erforderlichen Aktionen. Änderungen an Ihrem Shop werden jedoch nicht vorgenommen. <br><b>Beachten Sie, dass die Installationen zur ordnungsgemäßen Funktion des Modul-Connectors und der darauf aufbauenden Module unbedingt ausgeführt werden müssen.</b>',
    'D3_CFG_MOD_UPDATE_STEP_SKIP'                      => 'Installation vorläufig überspringen',
    'D3_CFG_MOD_UPDATE_STEP_SKIP_DESC'                 => 'Sie werden zu der ursprünglich gewählten Seite weitergeleitet. Die erforderlichen Installationen werden jedoch nicht ausgeführt. <br><b>Beachten Sie, dass die Installationen zur ordnungsgemäßen Funktion des Modul-Connectors und der darauf aufbauenden Module unbedingt ausgeführt werden müssen.</b>',
    'D3_CFG_MOD_UPDATE_STEP_SKIP_RANGE1'               => '<br>In frühestens ',
    'D3_CFG_MOD_UPDATE_STEP_SKIP_RANGE2'               => ' werden Sie wieder daran erinnert.',
    'D3_CFG_MOD_UPDATE_MULTIDESC'                      => 'Das Update muss in mehreren Schritten durchgeführt werden. Klicken Sie auf den Button, um die weiteren Schritte durchzuführen.',
    'D3_CFG_MOD_UPDATE_MULTICONTINUE'                  => 'Update fortsetzen',
    'D3_CFG_MOD_UPDATE_STEPCONTINUE'                   => 'Installationsschritt ausführen...',
    'D3_CFG_MOD_UPDATE_SESSIONSKIP'                    => 'in dieser Session überspringen',
    'D3_CFG_MOD_UPDATE_SKIPEVER'                       => 'immer überspringen',
    'D3_CFG_MOD_UPDATE_MULTIBACK'                      => 'zurück zur Aktionsauswahl',
    'D3_CFG_MOD_UPDATE_JOB_SQL'                        => 'Führen Sie diese Abfrage in Ihrer Shopdatenbank aus. Leeren Sie nach Abschluss der Installation den TMP-Ordner und aktualisieren Sie die VIEW-Tabellen:',
    'D3_CFG_MOD_UPDATE_JOB_MODULE'                     => 'Aktivieren Sie diese Module:',
    'D3_CFG_MOD_UPDATE_JOB_MSG'                        => 'Beachten Sie bitte die folgenden Hinweise:',
    'D3_CFG_MOD_UPDATE_JOB_FILECONTENT'                => 'Passen Sie die Datei "%s" so an oder legen Sie diese mit dem Inhalt neu an:',
    'D3_CFG_MOD_UPDATE_ACTIVATEMODULE'                 => 'Modul "%s" (ID: "%s") im Shop "%s (%s)"',
    'D3_CFG_MOD_UPDATE_JOB_BREAK'                      => 'Das Update wurde pausiert, da die weiteren Aktionen von den bisher gezeigten Updates abhängen. Führen Sie zuerst die bisherigen Updates aus und setzen Sie diesen Assistenten fort. Sie sehen dann an dieser Stelle die weiteren Updateschritte.',
    'D3_CFG_MOD_UPDATE_JOB_ERROR'                      => 'Fehler bei der Installation',
    'D3_CFG_MOD_UPDATE_JOB_ERROR_DESC'                 => 'Die Installation konnte für den gezeigten Schritt leider nicht durchgeführt werden. Bitte prüfen Sie diese Ausführung manuell und setzen dann die Installation hier fort.',
    'D3_CFG_MOD_UPDATE_JOB_ERRORMSG_DESC'              => 'Die Installation konnte für den gezeigten Schritt leider nicht durchgeführt werden. Die folgende Meldung wurde zurückgegeben: <code>%s</code>. Bitte prüfen Sie diese Ausführung manuell und setzen dann die Installation hier fort.',
    'D3_CFG_MOD_UPDATE_WAIT'                           => 'Please wait...',
    'D3_CFG_MOD_UPDATE_NOUPDATE'                       => 'There are no (further) updates required for your shop.',
    'D3_CFG_MOD_UPDATE_NOUPDATEBACKLINK'               => 'Click <a href="%s">here</a>, to go back to the former page.',
    'D3_CFG_MOD_UPDATE_HASSKIPHASHES'                  => 'In Ihrem Shop sind Updateaktionen vermerkt, die übersprungen werden sollen. Sollen diese Updateschritte wieder aktiviert werden?',
    'D3_CFG_MOD_UPDATE_DELSKIPHASHES'                  => 'übersprungene Updates wieder aktivieren',
    'D3_CFG_MOD_UPDATE_MOREINFO'                       => '[ mehr ... ]',
    'D3_CFG_MOD_UPDATE_STEP_CHECK_SAVEASFILE'          => 'als Datei exportieren',
    'D3_CFG_MOD_EXC_ALLLIBSDEACTIVATED'                => 'Aus Gründen der Systemstabilität wurden mit dieser Bibliothek auch alle damit verknüpften Biblotheken deaktiviert. Beachten Sie bitte, dass Module, die den D3 Modul-Connector erfordern, nun wahrscheinlich nicht mehr funktionieren, bevor der Modul-Connector wieder komplett aktiviert wurde.',
);


/*

[{oxmultilang ident="GENERAL_YOUWANTTODELETE"}]


*/
